/*
 * FILE : vgridlib.c
 * 
 * This file was automatically generated by :
 * Simplified Wrapper and Interface Generator (SWIG)
 * Version 1.1 (Patch 5)
 * 
 * Portions Copyright (c) 1995-1998
 * The University of Utah and The Regents of the University of California.
 * Permission is granted to distribute this file in any manner provided
 * this notice remains intact.
 * 
 * Do not make changes to this file--changes will be lost!
 *
 */


#define SWIGCODE
/* Implementation : PYTHON */

#define SWIGPYTHON
#include <string.h>
#include <stdlib.h>
/***********************************************************************
 * $Header$
 * swig_lib/python/python.cfg
 *
 * This file contains coded needed to add variable linking to the
 * Python interpreter.   C variables are added as a new kind of Python
 * datatype.
 *
 * Also contains supporting code for building python under Windows
 * and things like that.
 *
 * $Log$
 * Revision 1.2  2004/12/14 19:28:50  apbs
 * TJD:  Added python/vgrid to autoconf script.  Should compile when the rest of the Python wrapper compilation is enabled.
 *
 ************************************************************************/

#ifdef __cplusplus
extern "C" {
#endif
#include "Python.h"
#ifdef __cplusplus
}
#endif

/* Definitions for Windows/Unix exporting */
#if defined(__WIN32__)
#   if defined(_MSC_VER)
#	define SWIGEXPORT(a,b) __declspec(dllexport) a b
#   else
#	if defined(__BORLANDC__)
#	    define SWIGEXPORT(a,b) a _export b
#	else
#	    define SWIGEXPORT(a,b) a b
#	endif
#   endif
#else
#   define SWIGEXPORT(a,b) a b
#endif

#ifdef SWIG_GLOBAL
#ifdef __cplusplus
#define SWIGSTATIC extern "C"
#else
#define SWIGSTATIC
#endif
#endif

#ifndef SWIGSTATIC
#define SWIGSTATIC static
#endif

typedef struct {
  char  *name;
  PyObject *(*get_attr)(void);
  int (*set_attr)(PyObject *);
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar **vars;
  int      nvars;
  int      maxvars;
} swig_varlinkobject;

/* ----------------------------------------------------------------------
   swig_varlink_repr()

   Function for python repr method
   ---------------------------------------------------------------------- */

static PyObject *
swig_varlink_repr(swig_varlinkobject *v)
{
  v = v;
  return PyString_FromString("<Global variables>");
}

/* ---------------------------------------------------------------------
   swig_varlink_print()

   Print out all of the global variable names
   --------------------------------------------------------------------- */

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags)
{

  int i = 0;
  flags = flags;
  fprintf(fp,"Global variables { ");
  while (v->vars[i]) {
    fprintf(fp,"%s", v->vars[i]->name);
    i++;
    if (v->vars[i]) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

/* --------------------------------------------------------------------
   swig_varlink_getattr
 
   This function gets the value of a variable and returns it as a
   PyObject.   In our case, we'll be looking at the datatype and
   converting into a number or string
   -------------------------------------------------------------------- */

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n)
{
  int i = 0;
  char temp[128];

  while (v->vars[i]) {
    if (strcmp(v->vars[i]->name,n) == 0) {
      return (*v->vars[i]->get_attr)();
    }
    i++;
  }
  sprintf(temp,"C global variable %s not found.", n);
  PyErr_SetString(PyExc_NameError,temp);
  return NULL;
}

/* -------------------------------------------------------------------
   swig_varlink_setattr()

   This function sets the value of a variable.
   ------------------------------------------------------------------- */

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p)
{
  char temp[128];
  int i = 0;
  while (v->vars[i]) {
    if (strcmp(v->vars[i]->name,n) == 0) {
      return (*v->vars[i]->set_attr)(p);
    }
    i++;
  }
  sprintf(temp,"C global variable %s not found.", n);
  PyErr_SetString(PyExc_NameError,temp);
  return 1;
}

statichere PyTypeObject varlinktype = {
/*  PyObject_HEAD_INIT(&PyType_Type)  Note : This doesn't work on some machines */
  PyObject_HEAD_INIT(0)              
  0,
  "varlink",                          /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */

SWIGSTATIC PyObject *
SWIG_newvarlink(void)
{
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  /*  _Py_NewReference(result);  Does not seem to be necessary */
  result->nvars = 0;
  result->maxvars = 64;
  result->vars = (swig_globalvar **) malloc(64*sizeof(swig_globalvar *));
  result->vars[0] = 0;
  result->ob_refcnt = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGSTATIC void
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p))
{
  swig_varlinkobject *v;
  v= (swig_varlinkobject *) p;
	
  if (v->nvars >= v->maxvars -1) {
    v->maxvars = 2*v->maxvars;
    v->vars = (swig_globalvar **) realloc(v->vars,v->maxvars*sizeof(swig_globalvar *));
    if (v->vars == NULL) {
      fprintf(stderr,"SWIG : Fatal error in initializing Python module.\n");
      exit(1);
    }
  }
  v->vars[v->nvars] = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  v->vars[v->nvars]->name = (char *) malloc(strlen(name)+1);
  strcpy(v->vars[v->nvars]->name,name);
  v->vars[v->nvars]->get_attr = get_attr;
  v->vars[v->nvars]->set_attr = set_attr;
  v->nvars++;
  v->vars[v->nvars] = 0;
}



/*****************************************************************************
 * $Header$
 *
 * swigptr.swg
 *
 * This file contains supporting code for the SWIG run-time type checking
 * mechanism.  The following functions are available :
 *
 * SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *));
 *
 *      Registers a new type-mapping with the type-checker.  origtype is the
 *      original datatype and newtype is an equivalent type.  cast is optional
 *      pointer to a function to cast pointer values between types (this
 *      is typically used to cast pointers from derived classes to base classes in C++)
 *      
 * SWIG_MakePtr(char *buffer, void *ptr, char *typestring);
 *     
 *      Makes a pointer string from a pointer and typestring.  The result is returned
 *      in buffer which is assumed to hold enough space for the result.
 *
 * char * SWIG_GetPtr(char *buffer, void **ptr, char *type)
 *
 *      Gets a pointer value from a string.  If there is a type-mismatch, returns
 *      a character string to the received type.  On success, returns NULL.
 *
 *
 * You can remap these functions by making a file called "swigptr.swg" in
 * your the same directory as the interface file you are wrapping.
 *
 * These functions are normally declared static, but this file can be
 * can be used in a multi-module environment by redefining the symbol
 * SWIGSTATIC.
 *****************************************************************************/

#include <stdlib.h>

#ifdef SWIG_GLOBAL
#ifdef __cplusplus
#define SWIGSTATIC extern "C"
#else
#define SWIGSTATIC
#endif
#endif

#ifndef SWIGSTATIC
#define SWIGSTATIC static
#endif


/* SWIG pointer structure */

typedef struct SwigPtrType {
  char               *name;               /* Datatype name                  */
  int                 len;                /* Length (used for optimization) */
  void               *(*cast)(void *);    /* Pointer casting function       */
  struct SwigPtrType *next;               /* Linked list pointer            */
} SwigPtrType;

/* Pointer cache structure */

typedef struct {
  int                 stat;               /* Status (valid) bit             */
  SwigPtrType        *tp;                 /* Pointer to type structure      */
  char                name[256];          /* Given datatype name            */
  char                mapped[256];        /* Equivalent name                */
} SwigCacheType;

/* Some variables  */

static int SwigPtrMax  = 64;           /* Max entries that can be currently held */
                                       /* This value may be adjusted dynamically */
static int SwigPtrN    = 0;            /* Current number of entries              */
static int SwigPtrSort = 0;            /* Status flag indicating sort            */
static int SwigStart[256];             /* Starting positions of types            */

/* Pointer table */
static SwigPtrType *SwigPtrTable = 0;  /* Table containing pointer equivalences  */

/* Cached values */

#define SWIG_CACHESIZE  8
#define SWIG_CACHEMASK  0x7
static SwigCacheType SwigCache[SWIG_CACHESIZE];  
static int SwigCacheIndex = 0;
static int SwigLastCache = 0;

/* Sort comparison function */
static int swigsort(const void *data1, const void *data2) {
	SwigPtrType *d1 = (SwigPtrType *) data1;
	SwigPtrType *d2 = (SwigPtrType *) data2;
	return strcmp(d1->name,d2->name);
}

/* Binary Search function */
static int swigcmp(const void *key, const void *data) {
  char *k = (char *) key;
  SwigPtrType *d = (SwigPtrType *) data;
  return strncmp(k,d->name,d->len);
}

/* Register a new datatype with the type-checker */

SWIGSTATIC 
void SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *)) {

  int i;
  SwigPtrType *t = 0,*t1;

  /* Allocate the pointer table if necessary */

  if (!SwigPtrTable) {     
    SwigPtrTable = (SwigPtrType *) malloc(SwigPtrMax*sizeof(SwigPtrType));
    SwigPtrN = 0;
  }
  /* Grow the table */
  if (SwigPtrN >= SwigPtrMax) {
    SwigPtrMax = 2*SwigPtrMax;
    SwigPtrTable = (SwigPtrType *) realloc((char *) SwigPtrTable,SwigPtrMax*sizeof(SwigPtrType));
  }
  for (i = 0; i < SwigPtrN; i++)
    if (strcmp(SwigPtrTable[i].name,origtype) == 0) {
      t = &SwigPtrTable[i];
      break;
    }
  if (!t) {
    t = &SwigPtrTable[SwigPtrN];
    t->name = origtype;
    t->len = strlen(t->name);
    t->cast = 0;
    t->next = 0;
    SwigPtrN++;
  }

  /* Check for existing entry */

  while (t->next) {
    if ((strcmp(t->name,newtype) == 0)) {
      if (cast) t->cast = cast;
      return;
    }
    t = t->next;
  }
  
  /* Now place entry (in sorted order) */

  t1 = (SwigPtrType *) malloc(sizeof(SwigPtrType));
  t1->name = newtype;
  t1->len = strlen(t1->name);
  t1->cast = cast;
  t1->next = 0;            
  t->next = t1;           
  SwigPtrSort = 0;
}

/* Make a pointer value string */

SWIGSTATIC 
void SWIG_MakePtr(char *_c, const void *_ptr, char *type) {
  static char _hex[16] =
  {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
   'a', 'b', 'c', 'd', 'e', 'f'};
  unsigned long _p, _s;
  char _result[20], *_r;    /* Note : a 64-bit hex number = 16 digits */
  _r = _result;
  _p = (unsigned long) _ptr;
  if (_p > 0) {
    while (_p > 0) {
      _s = _p & 0xf;
      *(_r++) = _hex[_s];
      _p = _p >> 4;
    }
    *_r = '_';
    while (_r >= _result)
      *(_c++) = *(_r--);
  } else {
    strcpy (_c, "NULL");
  }
  if (_ptr)
    strcpy (_c, type);
}

/* Define for backwards compatibility */

#define _swig_make_hex   SWIG_MakePtr 

/* Function for getting a pointer value */

SWIGSTATIC 
char *SWIG_GetPtr(char *_c, void **ptr, char *_t)
{
  unsigned long _p;
  char temp_type[256];
  char *name;
  int  i, len;
  SwigPtrType *sp,*tp;
  SwigCacheType *cache;
  int  start, end;
  _p = 0;

  /* Pointer values must start with leading underscore */
  if (*_c == '_') {
      _c++;
      /* Extract hex value from pointer */
      while (*_c) {
	  if ((*_c >= '0') && (*_c <= '9'))
	    _p = (_p << 4) + (*_c - '0');
	  else if ((*_c >= 'a') && (*_c <= 'f'))
	    _p = (_p << 4) + ((*_c - 'a') + 10);
	  else
	    break;
	  _c++;
      }

      if (_t) {
	if (strcmp(_t,_c)) { 
	  if (!SwigPtrSort) {
	    qsort((void *) SwigPtrTable, SwigPtrN, sizeof(SwigPtrType), swigsort); 
	    for (i = 0; i < 256; i++) {
	      SwigStart[i] = SwigPtrN;
	    }
	    for (i = SwigPtrN-1; i >= 0; i--) {
	      SwigStart[(int) (SwigPtrTable[i].name[1])] = i;
	    }
	    for (i = 255; i >= 1; i--) {
	      if (SwigStart[i-1] > SwigStart[i])
		SwigStart[i-1] = SwigStart[i];
	    }
	    SwigPtrSort = 1;
	    for (i = 0; i < SWIG_CACHESIZE; i++)  
	      SwigCache[i].stat = 0;
	  }
	  
	  /* First check cache for matches.  Uses last cache value as starting point */
	  cache = &SwigCache[SwigLastCache];
	  for (i = 0; i < SWIG_CACHESIZE; i++) {
	    if (cache->stat) {
	      if (strcmp(_t,cache->name) == 0) {
		if (strcmp(_c,cache->mapped) == 0) {
		  cache->stat++;
		  *ptr = (void *) _p;
		  if (cache->tp->cast) *ptr = (*(cache->tp->cast))(*ptr);
		  return (char *) 0;
		}
	      }
	    }
	    SwigLastCache = (SwigLastCache+1) & SWIG_CACHEMASK;
	    if (!SwigLastCache) cache = SwigCache;
	    else cache++;
	  }
	  /* We have a type mismatch.  Will have to look through our type
	     mapping table to figure out whether or not we can accept this datatype */

	  start = SwigStart[(int) _t[1]];
	  end = SwigStart[(int) _t[1]+1];
	  sp = &SwigPtrTable[start];
	  while (start < end) {
	    if (swigcmp(_t,sp) == 0) break;
	    sp++;
	    start++;
	  }
	  if (start >= end) sp = 0;
	  /* Try to find a match for this */
	  if (sp) {
	    while (swigcmp(_t,sp) == 0) {
	      name = sp->name;
	      len = sp->len;
	      tp = sp->next;
	      /* Try to find entry for our given datatype */
	      while(tp) {
		if (tp->len >= 255) {
		  return _c;
		}
		strcpy(temp_type,tp->name);
		strncat(temp_type,_t+len,255-tp->len);
		if (strcmp(_c,temp_type) == 0) {
		  
		  strcpy(SwigCache[SwigCacheIndex].mapped,_c);
		  strcpy(SwigCache[SwigCacheIndex].name,_t);
		  SwigCache[SwigCacheIndex].stat = 1;
		  SwigCache[SwigCacheIndex].tp = tp;
		  SwigCacheIndex = SwigCacheIndex & SWIG_CACHEMASK;
		  
		  /* Get pointer value */
		  *ptr = (void *) _p;
		  if (tp->cast) *ptr = (*(tp->cast))(*ptr);
		  return (char *) 0;
		}
		tp = tp->next;
	      }
	      sp++;
	      /* Hmmm. Didn't find it this time */
	    }
	  }
	  /* Didn't find any sort of match for this data.  
	     Get the pointer value and return the received type */
	  *ptr = (void *) _p;
	  return _c;
	} else {
	  /* Found a match on the first try.  Return pointer value */
	  *ptr = (void *) _p;
	  return (char *) 0;
	}
      } else {
	/* No type specified.  Good luck */
	*ptr = (void *) _p;
	return (char *) 0;
      }
  } else {
    if (strcmp (_c, "NULL") == 0) {
	*ptr = (void *) 0;
	return (char *) 0;
    }
    *ptr = (void *) 0;	
    return _c;
  }
}

/* Compatibility mode */

#define _swig_get_hex  SWIG_GetPtr

#define SWIG_init    initvgridc

#define SWIG_name    "vgridc"

#include "routines.h"
#include "apbs/vgrid.h"


#include <ctype.h>

/*------------------------------------------------------------------
  ptrcast(value,type)

  Constructs a new pointer value.   Value may either be a string
  or an integer. Type is a string corresponding to either the
  C datatype or mangled datatype.

  ptrcast(0,"Vector *")
               or
  ptrcast(0,"Vector_p")   
  ------------------------------------------------------------------ */

static PyObject *ptrcast(PyObject *_PTRVALUE, char *type) {

  char *r,*s;
  void *ptr;
  PyObject *obj;
  char *typestr,*c;

  /* Produce a "mangled" version of the type string.  */

  typestr = (char *) malloc(strlen(type)+2);
  
  /* Go through and munge the typestring */
  
  r = typestr;
  *(r++) = '_';
  c = type;
  while (*c) {
    if (!isspace(*c)) {
      if ((*c == '*') || (*c == '&')) {
	*(r++) = 'p';
      }
      else *(r++) = *c;
    } else {
        *(r++) = '_';
    }
    c++;
  }
  *(r++) = 0;

  /* Check to see what kind of object _PTRVALUE is */
  
  if (PyInt_Check(_PTRVALUE)) {
    ptr = (void *) PyInt_AsLong(_PTRVALUE);
    /* Received a numerical value. Make a pointer out of it */
    r = (char *) malloc(strlen(typestr)+22);
    if (ptr) {
      SWIG_MakePtr(r, ptr, typestr);
    } else {
      sprintf(r,"_0%s",typestr);
    }
    obj = PyString_FromString(r);
    free(r);
  } else if (PyString_Check(_PTRVALUE)) {
    /* Have a real pointer value now.  Try to strip out the pointer
       value */
    s = PyString_AsString(_PTRVALUE);
    r = (char *) malloc(strlen(type)+22);
    
    /* Now extract the pointer value */
    if (!SWIG_GetPtr(s,&ptr,0)) {
      if (ptr) {
	SWIG_MakePtr(r,ptr,typestr);
      } else {
	sprintf(r,"_0%s",typestr);
      }
      obj = PyString_FromString(r);
    } else {
      obj = NULL;
    }
    free(r);
  } else {
    obj = NULL;
  }
  free(typestr);
  if (!obj) 
    PyErr_SetString(PyExc_TypeError,"Type error in ptrcast. Argument is not a valid pointer value.");
  return obj;
}

/*------------------------------------------------------------------
  ptrvalue(ptr,type = 0)

  Attempts to dereference a pointer value.  If type is given, it 
  will try to use that type.  Otherwise, this function will attempt
  to "guess" the proper datatype by checking against all of the 
  builtin C datatypes. 
  ------------------------------------------------------------------ */

static PyObject *ptrvalue(PyObject *_PTRVALUE, int index, char *type) {
  void     *ptr;
  char     *s;
  PyObject *obj;

  if (!PyString_Check(_PTRVALUE)) {
    PyErr_SetString(PyExc_TypeError,"Type error in ptrvalue. Argument is not a valid pointer value.");
    return NULL;
  }
  s = PyString_AsString(_PTRVALUE);
  if (SWIG_GetPtr(s,&ptr,0)) {
    PyErr_SetString(PyExc_TypeError,"Type error in ptrvalue. Argument is not a valid pointer value.");
    return NULL;
  }

  /* If no datatype was passed, try a few common datatypes first */

  if (!type) {

    /* No datatype was passed.   Type to figure out if it's a common one */

    if (!SWIG_GetPtr(s,&ptr,"_int_p")) {
      type = "int";
    } else if (!SWIG_GetPtr(s,&ptr,"_double_p")) {
      type = "double";
    } else if (!SWIG_GetPtr(s,&ptr,"_short_p")) {
      type = "short";
    } else if (!SWIG_GetPtr(s,&ptr,"_long_p")) {
      type = "long";
    } else if (!SWIG_GetPtr(s,&ptr,"_float_p")) {
      type = "float";
    } else if (!SWIG_GetPtr(s,&ptr,"_char_p")) {
      type = "char";
    } else if (!SWIG_GetPtr(s,&ptr,"_char_pp")) {
      type = "char *";
    } else {
      type = "unknown";
    }
  }

  if (!ptr) {
    PyErr_SetString(PyExc_TypeError,"Unable to dereference NULL pointer.");
    return NULL;
  }

  /* Now we have a datatype.  Try to figure out what to do about it */
  if (strcmp(type,"int") == 0) {
    obj = PyInt_FromLong((long) *(((int *) ptr) + index));
  } else if (strcmp(type,"double") == 0) {
    obj = PyFloat_FromDouble((double) *(((double *) ptr)+index));
  } else if (strcmp(type,"short") == 0) {
    obj = PyInt_FromLong((long) *(((short *) ptr)+index));
  } else if (strcmp(type,"long") == 0) {
    obj = PyInt_FromLong((long) *(((long *) ptr)+index));
  } else if (strcmp(type,"float") == 0) {
    obj = PyFloat_FromDouble((double) *(((float *) ptr)+index));
  } else if (strcmp(type,"char") == 0) {
    obj = PyString_FromString(((char *) ptr)+index);
  } else if (strcmp(type,"char *") == 0) {
    char *c = *(((char **) ptr)+index);
    if (c) obj = PyString_FromString(c);
    else obj = PyString_FromString("NULL");
  } else {
    PyErr_SetString(PyExc_TypeError,"Unable to dereference unsupported datatype.");
    return NULL;
  }
  return obj;
}

/*------------------------------------------------------------------
  ptrcreate(type,value = 0,numelements = 1)

  Attempts to create a new object of given type.  Type must be
  a basic C datatype.  Will not create complex objects.
  ------------------------------------------------------------------ */

static PyObject *ptrcreate(char *type, PyObject *_PYVALUE, int numelements) {
  void     *ptr;
  PyObject *obj;
  int       sz;
  char     *cast;
  char      temp[40];

  /* Check the type string against a variety of possibilities */

  if (strcmp(type,"int") == 0) {
    sz = sizeof(int)*numelements;
    cast = "_int_p";
  } else if (strcmp(type,"short") == 0) {
    sz = sizeof(short)*numelements;
    cast = "_short_p";
  } else if (strcmp(type,"long") == 0) {
    sz = sizeof(long)*numelements;
    cast = "_long_p";
  } else if (strcmp(type,"double") == 0) {
    sz = sizeof(double)*numelements;
    cast = "_double_p";
  } else if (strcmp(type,"float") == 0) {
    sz = sizeof(float)*numelements;
    cast = "_float_p";
  } else if (strcmp(type,"char") == 0) {
    sz = sizeof(char)*numelements;
    cast = "_char_p";
  } else if (strcmp(type,"char *") == 0) {
    sz = sizeof(char *)*(numelements+1);
    cast = "_char_pp";
  } else {
    PyErr_SetString(PyExc_TypeError,"Unable to create unknown datatype."); 
    return NULL;
  }
   
  /* Create the new object */
  
  ptr = (void *) malloc(sz);
  if (!ptr) {
    PyErr_SetString(PyExc_MemoryError,"Out of memory in swig_create."); 
    return NULL;
  }

  /* Now try to set its default value */

  if (_PYVALUE) {
    if (strcmp(type,"int") == 0) {
      int *ip,i,ivalue;
      ivalue = (int) PyInt_AsLong(_PYVALUE);
      ip = (int *) ptr;
      for (i = 0; i < numelements; i++)
	ip[i] = ivalue;
    } else if (strcmp(type,"short") == 0) {
      short *ip,ivalue;
      int i;
      ivalue = (short) PyInt_AsLong(_PYVALUE);
      ip = (short *) ptr;
      for (i = 0; i < numelements; i++)
	ip[i] = ivalue;
    } else if (strcmp(type,"long") == 0) {
      long *ip,ivalue;
      int i;
      ivalue = (long) PyInt_AsLong(_PYVALUE);
      ip = (long *) ptr;
      for (i = 0; i < numelements; i++)
	ip[i] = ivalue;
    } else if (strcmp(type,"double") == 0) {
      double *ip,ivalue;
      int i;
      ivalue = (double) PyFloat_AsDouble(_PYVALUE);
      ip = (double *) ptr;
      for (i = 0; i < numelements; i++)
	ip[i] = ivalue;
    } else if (strcmp(type,"float") == 0) {
      float *ip,ivalue;
      int i;
      ivalue = (float) PyFloat_AsDouble(_PYVALUE);
      ip = (float *) ptr;
      for (i = 0; i < numelements; i++)
	ip[i] = ivalue;
    } else if (strcmp(type,"char") == 0) {
      char *ip,*ivalue;
      ivalue = (char *) PyString_AsString(_PYVALUE);
      ip = (char *) ptr;
      strncpy(ip,ivalue,numelements-1);
    } else if (strcmp(type,"char *") == 0) {
      char **ip, *ivalue;
      int  i;
      ivalue = (char *) PyString_AsString(_PYVALUE);
      ip = (char **) ptr;
      for (i = 0; i < numelements; i++) {
	if (ivalue) {
	  ip[i] = (char *) malloc(strlen(ivalue)+1);
	  strcpy(ip[i],ivalue);
	} else {
	  ip[i] = 0;
	}
      }
      ip[numelements] = 0;
    }
  } 
  /* Create the pointer value */
  
  SWIG_MakePtr(temp,ptr,cast);
  obj = PyString_FromString(temp);
  return obj;
}


/*------------------------------------------------------------------
  ptrset(ptr,value,index = 0,type = 0)

  Attempts to set the value of a pointer variable.  If type is
  given, we will use that type.  Otherwise, we'll guess the datatype.
  ------------------------------------------------------------------ */

static PyObject *ptrset(PyObject *_PTRVALUE, PyObject *_PYVALUE, int index, char *type) {
  void     *ptr;
  char     *s;
  PyObject *obj;

  if (!PyString_Check(_PTRVALUE)) {
    PyErr_SetString(PyExc_TypeError,"Type error in ptrset. Argument is not a valid pointer value.");
    return NULL;
  }
  s = PyString_AsString(_PTRVALUE);
  if (SWIG_GetPtr(s,&ptr,0)) {
    PyErr_SetString(PyExc_TypeError,"Type error in ptrset. Argument is not a valid pointer value.");
    return NULL;
  }

  /* If no datatype was passed, try a few common datatypes first */

  if (!type) {

    /* No datatype was passed.   Type to figure out if it's a common one */

    if (!SWIG_GetPtr(s,&ptr,"_int_p")) {
      type = "int";
    } else if (!SWIG_GetPtr(s,&ptr,"_double_p")) {
      type = "double";
    } else if (!SWIG_GetPtr(s,&ptr,"_short_p")) {
      type = "short";
    } else if (!SWIG_GetPtr(s,&ptr,"_long_p")) {
      type = "long";
    } else if (!SWIG_GetPtr(s,&ptr,"_float_p")) {
      type = "float";
    } else if (!SWIG_GetPtr(s,&ptr,"_char_p")) {
      type = "char";
    } else if (!SWIG_GetPtr(s,&ptr,"_char_pp")) {
      type = "char *";
    } else {
      type = "unknown";
    }
  }

  if (!ptr) {
    PyErr_SetString(PyExc_TypeError,"Unable to set NULL pointer.");
    return NULL;
  }
  
  /* Now we have a datatype.  Try to figure out what to do about it */
  if (strcmp(type,"int") == 0) {
    *(((int *) ptr)+index) = (int) PyInt_AsLong(_PYVALUE);
  } else if (strcmp(type,"double") == 0) {
    *(((double *) ptr)+index) = (double) PyFloat_AsDouble(_PYVALUE);
  } else if (strcmp(type,"short") == 0) {
    *(((short *) ptr)+index) = (short) PyInt_AsLong(_PYVALUE);
  } else if (strcmp(type,"long") == 0) {
    *(((long *) ptr)+index) = (long) PyInt_AsLong(_PYVALUE);
  } else if (strcmp(type,"float") == 0) {
    *(((float *) ptr)+index) = (float) PyFloat_AsDouble(_PYVALUE);
  } else if (strcmp(type,"char") == 0) {
    char *c = PyString_AsString(_PYVALUE);
    strcpy(((char *) ptr)+index, c);
  } else if (strcmp(type,"char *") == 0) {
    char *c = PyString_AsString(_PYVALUE);
    char **ca = (char **) ptr;
    if (ca[index]) free(ca[index]);
    if (strcmp(c,"NULL") == 0) {
      ca[index] = 0;
    } else {
      ca[index] = (char *) malloc(strlen(c)+1);
      strcpy(ca[index],c);
    }
  } else {
    PyErr_SetString(PyExc_TypeError,"Unable to set unsupported datatype.");
    return NULL;
  }
  Py_INCREF(Py_None);
  return Py_None;
}


/*------------------------------------------------------------------
  ptradd(ptr,offset)

  Adds a value to an existing pointer value.  Will do a type-dependent
  add for basic datatypes.  For other datatypes, will do a byte-add.
  ------------------------------------------------------------------ */

static PyObject *ptradd(PyObject *_PTRVALUE, int offset) {

  char *r,*s;
  void *ptr,*junk;
  PyObject *obj;
  char *type;

  /* Check to see what kind of object _PTRVALUE is */
  
  if (PyString_Check(_PTRVALUE)) {
    /* Have a potential pointer value now.  Try to strip out the value */
    s = PyString_AsString(_PTRVALUE);

    /* Try to handle a few common datatypes first */

    if (!SWIG_GetPtr(s,&ptr,"_int_p")) {
      ptr = (void *) (((int *) ptr) + offset);
    } else if (!SWIG_GetPtr(s,&ptr,"_double_p")) {
      ptr = (void *) (((double *) ptr) + offset);
    } else if (!SWIG_GetPtr(s,&ptr,"_short_p")) {
      ptr = (void *) (((short *) ptr) + offset);
    } else if (!SWIG_GetPtr(s,&ptr,"_long_p")) {
      ptr = (void *) (((long *) ptr) + offset);
    } else if (!SWIG_GetPtr(s,&ptr,"_float_p")) {
      ptr = (void *) (((float *) ptr) + offset);
    } else if (!SWIG_GetPtr(s,&ptr,"_char_p")) {
      ptr = (void *) (((char *) ptr) + offset);
    } else if (!SWIG_GetPtr(s,&ptr,0)) {
      ptr = (void *) (((char *) ptr) + offset);
    } else {
      PyErr_SetString(PyExc_TypeError,"Type error in ptradd. Argument is not a valid pointer value.");
      return NULL;
    }
    type = SWIG_GetPtr(s,&junk,"INVALID POINTER");
    r = (char *) malloc(strlen(type)+20);
    if (ptr) {
      SWIG_MakePtr(r,ptr,type);
    } else {
      sprintf(r,"_0%s",type);
    }
    obj = PyString_FromString(r);
    free(r);
  }
  return obj;
}

/*------------------------------------------------------------------
  ptrmap(type1,type2)

  Allows a mapping between type1 and type2. (Like a typedef)
  ------------------------------------------------------------------ */

static void ptrmap(char *type1, char *type2) {

  char *typestr1,*typestr2,*c,*r;

  /* Produce a "mangled" version of the type string.  */

  typestr1 = (char *) malloc(strlen(type1)+2);
  
  /* Go through and munge the typestring */
  
  r = typestr1;
  *(r++) = '_';
  c = type1;
  while (*c) {
    if (!isspace(*c)) {
      if ((*c == '*') || (*c == '&')) {
	*(r++) = 'p';
      }
      else *(r++) = *c;
    } else {
      *(r++) = '_';
    }
    c++;
  }
  *(r++) = 0;
  
  typestr2 = (char *) malloc(strlen(type2)+2);

  /* Go through and munge the typestring */
  
  r = typestr2;
  *(r++) = '_';
  c = type2;
  while (*c) {
    if (!isspace(*c)) {
      if ((*c == '*') || (*c == '&')) {
	*(r++) = 'p';
      }
      else *(r++) = *c;
    } else {
      *(r++) = '_';
    }
    c++;
  }
  *(r++) = 0;
  SWIG_RegisterMapping(typestr1,typestr2,0);
  SWIG_RegisterMapping(typestr2,typestr1,0);
}

/*------------------------------------------------------------------
  ptrfree(ptr)

  Destroys a pointer value
  ------------------------------------------------------------------ */

PyObject *ptrfree(PyObject *_PTRVALUE) {
  void *ptr, *junk;
  char *s;

  if (!PyString_Check(_PTRVALUE)) {
    PyErr_SetString(PyExc_TypeError,"Type error in ptrfree. Argument is not a valid pointer value.");
    return NULL;
  }
  s = PyString_AsString(_PTRVALUE);
  if (SWIG_GetPtr(s,&ptr,0)) {
    PyErr_SetString(PyExc_TypeError,"Type error in ptrfree. Argument is not a valid pointer value.");
    return NULL;
  }

  /* Check to see if this pointer is a char ** */
  if (!SWIG_GetPtr(s,&junk,"_char_pp")) {
    char **c = (char **) ptr;
    if (c) {
      int i = 0;
      while (c[i]) {
	free(c[i]);
	i++;
      }
    }
  } 
  if (ptr)
    free((char *) ptr);

  Py_INCREF(Py_None);
  return Py_None;
}


double *null_array(){
     return NULL;
}

double *double_array(int size) {
     return (double *) malloc(size*sizeof(double));
  }

double get_entry(double *array, int i){
	return array[i];
  }

void set_entry(double *array, int i, double val){
	array[i] = val;
  }

void delVgrid(Vgrid *thee){
    if (thee != VNULL) {
        Vmem_free(thee->mem, (thee->nx*thee->ny*thee->nz), sizeof(double),
          (void **)&(thee->data));
        Vmem_free(VNULL, 1, sizeof(Vgrid), (void **)&thee);
        thee = VNULL;
    }
}
extern Vgrid *Vgrid_ctor(int ,int ,int ,double ,double ,double ,double ,double ,double ,double *);
extern int Vgrid_ctor2(Vgrid *,int ,int ,int ,double ,double ,double ,double ,double ,double ,double *);
extern int Vgrid_value(Vgrid *,double [3],double *);
extern void Vgrid_dtor(Vgrid **);
extern void Vgrid_dtor2(Vgrid *);
extern int Vgrid_curvature(Vgrid *,double [3],int ,double *);
extern int Vgrid_gradient(Vgrid *,double [3],double [3]);
extern void Vgrid_writeUHBD(Vgrid *,const char *,const char *,const char *,const char *,char *,double *);
extern void Vgrid_writeDX(Vgrid *,const char *,const char *,const char *,const char *,char *,double *);
extern int Vgrid_readDX(Vgrid *,const char *,const char *,const char *,const char *);
extern void startVio();
static PyObject *_wrap_ptrcast(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    PyObject * _result;
    PyObject * _arg0;
    char * _arg1;
    PyObject * _obj0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Os:ptrcast",&_obj0,&_arg1)) 
        return NULL;
{
  _arg0 = _obj0;
}
    _result = (PyObject *)ptrcast(_arg0,_arg1);
{
  _resultobj = _result;
}
    return _resultobj;
}

static PyObject *_wrap_ptrvalue(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    PyObject * _result;
    PyObject * _arg0;
    int  _arg1 = 0;
    char * _arg2 = 0;
    PyObject * _obj0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O|is:ptrvalue",&_obj0,&_arg1,&_arg2)) 
        return NULL;
{
  _arg0 = _obj0;
}
    _result = (PyObject *)ptrvalue(_arg0,_arg1,_arg2);
{
  _resultobj = _result;
}
    return _resultobj;
}

static PyObject *_wrap_ptrset(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    PyObject * _result;
    PyObject * _arg0;
    PyObject * _arg1;
    int  _arg2 = 0;
    char * _arg3 = 0;
    PyObject * _obj0 = 0;
    PyObject * _obj1 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"OO|is:ptrset",&_obj0,&_obj1,&_arg2,&_arg3)) 
        return NULL;
{
  _arg0 = _obj0;
}
{
  _arg1 = _obj1;
}
    _result = (PyObject *)ptrset(_arg0,_arg1,_arg2,_arg3);
{
  _resultobj = _result;
}
    return _resultobj;
}

static PyObject *_wrap_ptrcreate(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    PyObject * _result;
    char * _arg0;
    PyObject * _arg1 = 0;
    int  _arg2 = 1;
    PyObject * _obj1 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s|Oi:ptrcreate",&_arg0,&_obj1,&_arg2)) 
        return NULL;
    if (_obj1)
{
  _arg1 = _obj1;
}
    _result = (PyObject *)ptrcreate(_arg0,_arg1,_arg2);
{
  _resultobj = _result;
}
    return _resultobj;
}

static PyObject *_wrap_ptrfree(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    PyObject * _result;
    PyObject * _arg0;
    PyObject * _obj0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"O:ptrfree",&_obj0)) 
        return NULL;
{
  _arg0 = _obj0;
}
    _result = (PyObject *)ptrfree(_arg0);
{
  _resultobj = _result;
}
    return _resultobj;
}

static PyObject *_wrap_ptradd(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    PyObject * _result;
    PyObject * _arg0;
    int  _arg1;
    PyObject * _obj0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"Oi:ptradd",&_obj0,&_arg1)) 
        return NULL;
{
  _arg0 = _obj0;
}
    _result = (PyObject *)ptradd(_arg0,_arg1);
{
  _resultobj = _result;
}
    return _resultobj;
}

static PyObject *_wrap_ptrmap(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    char * _arg0;
    char * _arg1;

    self = self;
    if(!PyArg_ParseTuple(args,"ss:ptrmap",&_arg0,&_arg1)) 
        return NULL;
    ptrmap(_arg0,_arg1);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_null_array(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double * _result;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,":null_array")) 
        return NULL;
    _result = (double *)null_array();
    SWIG_MakePtr(_ptemp, (char *) _result,"_double_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_double_array(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double * _result;
    int  _arg0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"i:double_array",&_arg0)) 
        return NULL;
    _result = (double *)double_array(_arg0);
    SWIG_MakePtr(_ptemp, (char *) _result,"_double_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_get_entry(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    double * _arg0;
    int  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"si:get_entry",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_double_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of get_entry. Expected _double_p.");
        return NULL;
        }
    }
    _result = (double )get_entry(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

static PyObject *_wrap_set_entry(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double * _arg0;
    int  _arg1;
    double  _arg2;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sid:set_entry",&_argc0,&_arg1,&_arg2)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_double_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of set_entry. Expected _double_p.");
        return NULL;
        }
    }
    set_entry(_arg0,_arg1,_arg2);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_delVgrid(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    Vgrid * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:delVgrid",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of delVgrid. Expected _Vgrid_p.");
        return NULL;
        }
    }
    delVgrid(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_Vgrid_ctor(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    Vgrid * _result;
    int  _arg0;
    int  _arg1;
    int  _arg2;
    double  _arg3;
    double  _arg4;
    double  _arg5;
    double  _arg6;
    double  _arg7;
    double  _arg8;
    double * _arg9;
    char * _argc9 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"iiidddddds:Vgrid_ctor",&_arg0,&_arg1,&_arg2,&_arg3,&_arg4,&_arg5,&_arg6,&_arg7,&_arg8,&_argc9)) 
        return NULL;
    if (_argc9) {
        if (SWIG_GetPtr(_argc9,(void **) &_arg9,"_double_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 10 of Vgrid_ctor. Expected _double_p.");
        return NULL;
        }
    }
    _result = (Vgrid *)Vgrid_ctor(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6,_arg7,_arg8,_arg9);
    SWIG_MakePtr(_ptemp, (char *) _result,"_Vgrid_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyObject *_wrap_Vgrid_ctor2(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    Vgrid * _arg0;
    int  _arg1;
    int  _arg2;
    int  _arg3;
    double  _arg4;
    double  _arg5;
    double  _arg6;
    double  _arg7;
    double  _arg8;
    double  _arg9;
    double * _arg10;
    char * _argc0 = 0;
    char * _argc10 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"siiidddddds:Vgrid_ctor2",&_argc0,&_arg1,&_arg2,&_arg3,&_arg4,&_arg5,&_arg6,&_arg7,&_arg8,&_arg9,&_argc10)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_ctor2. Expected _Vgrid_p.");
        return NULL;
        }
    }
    if (_argc10) {
        if (SWIG_GetPtr(_argc10,(void **) &_arg10,"_double_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 11 of Vgrid_ctor2. Expected _double_p.");
        return NULL;
        }
    }
    _result = (int )Vgrid_ctor2(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6,_arg7,_arg8,_arg9,_arg10);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_Vgrid_value(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    Vgrid * _arg0;
    double * _arg1;
    double * _arg2;
    char * _argc0 = 0;
    char * _argc1 = 0;
    char * _argc2 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sss:Vgrid_value",&_argc0,&_argc1,&_argc2)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_value. Expected _Vgrid_p.");
        return NULL;
        }
    }
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_double_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of Vgrid_value. Expected _double_p.");
        return NULL;
        }
    }
    if (_argc2) {
        if (SWIG_GetPtr(_argc2,(void **) &_arg2,"_double_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 3 of Vgrid_value. Expected _double_p.");
        return NULL;
        }
    }
    _result = (int )Vgrid_value(_arg0,_arg1,_arg2);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_Vgrid_dtor(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    Vgrid ** _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:Vgrid_dtor",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_pp")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_dtor. Expected _Vgrid_pp.");
        return NULL;
        }
    }
    Vgrid_dtor(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_Vgrid_dtor2(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    Vgrid * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:Vgrid_dtor2",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_dtor2. Expected _Vgrid_p.");
        return NULL;
        }
    }
    Vgrid_dtor2(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_Vgrid_curvature(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    Vgrid * _arg0;
    double * _arg1;
    int  _arg2;
    double * _arg3;
    char * _argc0 = 0;
    char * _argc1 = 0;
    char * _argc3 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"ssis:Vgrid_curvature",&_argc0,&_argc1,&_arg2,&_argc3)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_curvature. Expected _Vgrid_p.");
        return NULL;
        }
    }
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_double_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of Vgrid_curvature. Expected _double_p.");
        return NULL;
        }
    }
    if (_argc3) {
        if (SWIG_GetPtr(_argc3,(void **) &_arg3,"_double_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 4 of Vgrid_curvature. Expected _double_p.");
        return NULL;
        }
    }
    _result = (int )Vgrid_curvature(_arg0,_arg1,_arg2,_arg3);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_Vgrid_gradient(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    Vgrid * _arg0;
    double * _arg1;
    double * _arg2;
    char * _argc0 = 0;
    char * _argc1 = 0;
    char * _argc2 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sss:Vgrid_gradient",&_argc0,&_argc1,&_argc2)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_gradient. Expected _Vgrid_p.");
        return NULL;
        }
    }
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_double_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of Vgrid_gradient. Expected _double_p.");
        return NULL;
        }
    }
    if (_argc2) {
        if (SWIG_GetPtr(_argc2,(void **) &_arg2,"_double_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 3 of Vgrid_gradient. Expected _double_p.");
        return NULL;
        }
    }
    _result = (int )Vgrid_gradient(_arg0,_arg1,_arg2);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_Vgrid_writeUHBD(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    Vgrid * _arg0;
    char * _arg1;
    char * _arg2;
    char * _arg3;
    char * _arg4;
    char * _arg5;
    double * _arg6;
    char * _argc0 = 0;
    char * _argc6 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sssssss:Vgrid_writeUHBD",&_argc0,&_arg1,&_arg2,&_arg3,&_arg4,&_arg5,&_argc6)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_writeUHBD. Expected _Vgrid_p.");
        return NULL;
        }
    }
    if (_argc6) {
        if (SWIG_GetPtr(_argc6,(void **) &_arg6,"_double_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 7 of Vgrid_writeUHBD. Expected _double_p.");
        return NULL;
        }
    }
    Vgrid_writeUHBD(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_Vgrid_writeDX(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    Vgrid * _arg0;
    char * _arg1;
    char * _arg2;
    char * _arg3;
    char * _arg4;
    char * _arg5;
    double * _arg6;
    char * _argc0 = 0;
    char * _argc6 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sssssss:Vgrid_writeDX",&_argc0,&_arg1,&_arg2,&_arg3,&_arg4,&_arg5,&_argc6)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_writeDX. Expected _Vgrid_p.");
        return NULL;
        }
    }
    if (_argc6) {
        if (SWIG_GetPtr(_argc6,(void **) &_arg6,"_double_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 7 of Vgrid_writeDX. Expected _double_p.");
        return NULL;
        }
    }
    Vgrid_writeDX(_arg0,_arg1,_arg2,_arg3,_arg4,_arg5,_arg6);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

static PyObject *_wrap_Vgrid_readDX(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    Vgrid * _arg0;
    char * _arg1;
    char * _arg2;
    char * _arg3;
    char * _arg4;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sssss:Vgrid_readDX",&_argc0,&_arg1,&_arg2,&_arg3,&_arg4)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_readDX. Expected _Vgrid_p.");
        return NULL;
        }
    }
    _result = (int )Vgrid_readDX(_arg0,_arg1,_arg2,_arg3,_arg4);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

static PyObject *_wrap_startVio(PyObject *self, PyObject *args) {
    PyObject * _resultobj;

    self = self;
    if(!PyArg_ParseTuple(args,":startVio")) 
        return NULL;
    startVio();
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

#define new_Vgrid() ((Vgrid *) calloc(1,sizeof(Vgrid)))
static PyObject *_wrap_new_Vgrid(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    Vgrid * _result;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,":new_Vgrid")) 
        return NULL;
    _result = (Vgrid *)new_Vgrid();
    SWIG_MakePtr(_ptemp, (char *) _result,"_Vgrid_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

#define delete_Vgrid(_swigobj) (free ((char *) _swigobj))
static PyObject *_wrap_delete_Vgrid(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    Vgrid * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:delete_Vgrid",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of delete_Vgrid. Expected _Vgrid_p.");
        return NULL;
        }
    }
    delete_Vgrid(_arg0);
    Py_INCREF(Py_None);
    _resultobj = Py_None;
    return _resultobj;
}

#define Vgrid_nx_set(_swigobj,_swigval) (_swigobj->nx = _swigval,_swigval)
static PyObject *_wrap_Vgrid_nx_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    Vgrid * _arg0;
    int  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"si:Vgrid_nx_set",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_nx_set. Expected _Vgrid_p.");
        return NULL;
        }
    }
    _result = (int )Vgrid_nx_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define Vgrid_nx_get(_swigobj) ((int ) _swigobj->nx)
static PyObject *_wrap_Vgrid_nx_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    Vgrid * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:Vgrid_nx_get",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_nx_get. Expected _Vgrid_p.");
        return NULL;
        }
    }
    _result = (int )Vgrid_nx_get(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define Vgrid_ny_set(_swigobj,_swigval) (_swigobj->ny = _swigval,_swigval)
static PyObject *_wrap_Vgrid_ny_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    Vgrid * _arg0;
    int  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"si:Vgrid_ny_set",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_ny_set. Expected _Vgrid_p.");
        return NULL;
        }
    }
    _result = (int )Vgrid_ny_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define Vgrid_ny_get(_swigobj) ((int ) _swigobj->ny)
static PyObject *_wrap_Vgrid_ny_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    Vgrid * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:Vgrid_ny_get",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_ny_get. Expected _Vgrid_p.");
        return NULL;
        }
    }
    _result = (int )Vgrid_ny_get(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define Vgrid_nz_set(_swigobj,_swigval) (_swigobj->nz = _swigval,_swigval)
static PyObject *_wrap_Vgrid_nz_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    Vgrid * _arg0;
    int  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"si:Vgrid_nz_set",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_nz_set. Expected _Vgrid_p.");
        return NULL;
        }
    }
    _result = (int )Vgrid_nz_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define Vgrid_nz_get(_swigobj) ((int ) _swigobj->nz)
static PyObject *_wrap_Vgrid_nz_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    int  _result;
    Vgrid * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:Vgrid_nz_get",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_nz_get. Expected _Vgrid_p.");
        return NULL;
        }
    }
    _result = (int )Vgrid_nz_get(_arg0);
    _resultobj = Py_BuildValue("i",_result);
    return _resultobj;
}

#define Vgrid_hx_set(_swigobj,_swigval) (_swigobj->hx = _swigval,_swigval)
static PyObject *_wrap_Vgrid_hx_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    Vgrid * _arg0;
    double  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sd:Vgrid_hx_set",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_hx_set. Expected _Vgrid_p.");
        return NULL;
        }
    }
    _result = (double )Vgrid_hx_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define Vgrid_hx_get(_swigobj) ((double ) _swigobj->hx)
static PyObject *_wrap_Vgrid_hx_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    Vgrid * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:Vgrid_hx_get",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_hx_get. Expected _Vgrid_p.");
        return NULL;
        }
    }
    _result = (double )Vgrid_hx_get(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define Vgrid_hy_set(_swigobj,_swigval) (_swigobj->hy = _swigval,_swigval)
static PyObject *_wrap_Vgrid_hy_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    Vgrid * _arg0;
    double  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sd:Vgrid_hy_set",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_hy_set. Expected _Vgrid_p.");
        return NULL;
        }
    }
    _result = (double )Vgrid_hy_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define Vgrid_hy_get(_swigobj) ((double ) _swigobj->hy)
static PyObject *_wrap_Vgrid_hy_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    Vgrid * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:Vgrid_hy_get",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_hy_get. Expected _Vgrid_p.");
        return NULL;
        }
    }
    _result = (double )Vgrid_hy_get(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define Vgrid_hzed_set(_swigobj,_swigval) (_swigobj->hzed = _swigval,_swigval)
static PyObject *_wrap_Vgrid_hzed_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    Vgrid * _arg0;
    double  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sd:Vgrid_hzed_set",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_hzed_set. Expected _Vgrid_p.");
        return NULL;
        }
    }
    _result = (double )Vgrid_hzed_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define Vgrid_hzed_get(_swigobj) ((double ) _swigobj->hzed)
static PyObject *_wrap_Vgrid_hzed_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    Vgrid * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:Vgrid_hzed_get",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_hzed_get. Expected _Vgrid_p.");
        return NULL;
        }
    }
    _result = (double )Vgrid_hzed_get(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define Vgrid_xmin_set(_swigobj,_swigval) (_swigobj->xmin = _swigval,_swigval)
static PyObject *_wrap_Vgrid_xmin_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    Vgrid * _arg0;
    double  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sd:Vgrid_xmin_set",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_xmin_set. Expected _Vgrid_p.");
        return NULL;
        }
    }
    _result = (double )Vgrid_xmin_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define Vgrid_xmin_get(_swigobj) ((double ) _swigobj->xmin)
static PyObject *_wrap_Vgrid_xmin_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    Vgrid * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:Vgrid_xmin_get",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_xmin_get. Expected _Vgrid_p.");
        return NULL;
        }
    }
    _result = (double )Vgrid_xmin_get(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define Vgrid_ymin_set(_swigobj,_swigval) (_swigobj->ymin = _swigval,_swigval)
static PyObject *_wrap_Vgrid_ymin_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    Vgrid * _arg0;
    double  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sd:Vgrid_ymin_set",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_ymin_set. Expected _Vgrid_p.");
        return NULL;
        }
    }
    _result = (double )Vgrid_ymin_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define Vgrid_ymin_get(_swigobj) ((double ) _swigobj->ymin)
static PyObject *_wrap_Vgrid_ymin_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    Vgrid * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:Vgrid_ymin_get",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_ymin_get. Expected _Vgrid_p.");
        return NULL;
        }
    }
    _result = (double )Vgrid_ymin_get(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define Vgrid_zmin_set(_swigobj,_swigval) (_swigobj->zmin = _swigval,_swigval)
static PyObject *_wrap_Vgrid_zmin_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    Vgrid * _arg0;
    double  _arg1;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"sd:Vgrid_zmin_set",&_argc0,&_arg1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_zmin_set. Expected _Vgrid_p.");
        return NULL;
        }
    }
    _result = (double )Vgrid_zmin_set(_arg0,_arg1);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define Vgrid_zmin_get(_swigobj) ((double ) _swigobj->zmin)
static PyObject *_wrap_Vgrid_zmin_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double  _result;
    Vgrid * _arg0;
    char * _argc0 = 0;

    self = self;
    if(!PyArg_ParseTuple(args,"s:Vgrid_zmin_get",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_zmin_get. Expected _Vgrid_p.");
        return NULL;
        }
    }
    _result = (double )Vgrid_zmin_get(_arg0);
    _resultobj = Py_BuildValue("d",_result);
    return _resultobj;
}

#define Vgrid_data_set(_swigobj,_swigval) (_swigobj->data = _swigval,_swigval)
static PyObject *_wrap_Vgrid_data_set(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double * _result;
    Vgrid * _arg0;
    double * _arg1;
    char * _argc0 = 0;
    char * _argc1 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"ss:Vgrid_data_set",&_argc0,&_argc1)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_data_set. Expected _Vgrid_p.");
        return NULL;
        }
    }
    if (_argc1) {
        if (SWIG_GetPtr(_argc1,(void **) &_arg1,"_double_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 2 of Vgrid_data_set. Expected _double_p.");
        return NULL;
        }
    }
    _result = (double *)Vgrid_data_set(_arg0,_arg1);
    SWIG_MakePtr(_ptemp, (char *) _result,"_double_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

#define Vgrid_data_get(_swigobj) ((double *) _swigobj->data)
static PyObject *_wrap_Vgrid_data_get(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    double * _result;
    Vgrid * _arg0;
    char * _argc0 = 0;
    char _ptemp[128];

    self = self;
    if(!PyArg_ParseTuple(args,"s:Vgrid_data_get",&_argc0)) 
        return NULL;
    if (_argc0) {
        if (SWIG_GetPtr(_argc0,(void **) &_arg0,"_Vgrid_p")) {
            PyErr_SetString(PyExc_TypeError,"Type error in argument 1 of Vgrid_data_get. Expected _Vgrid_p.");
        return NULL;
        }
    }
    _result = (double *)Vgrid_data_get(_arg0);
    SWIG_MakePtr(_ptemp, (char *) _result,"_double_p");
    _resultobj = Py_BuildValue("s",_ptemp);
    return _resultobj;
}

static PyMethodDef vgridcMethods[] = {
	 { "Vgrid_data_get", _wrap_Vgrid_data_get, 1 },
	 { "Vgrid_data_set", _wrap_Vgrid_data_set, 1 },
	 { "Vgrid_zmin_get", _wrap_Vgrid_zmin_get, 1 },
	 { "Vgrid_zmin_set", _wrap_Vgrid_zmin_set, 1 },
	 { "Vgrid_ymin_get", _wrap_Vgrid_ymin_get, 1 },
	 { "Vgrid_ymin_set", _wrap_Vgrid_ymin_set, 1 },
	 { "Vgrid_xmin_get", _wrap_Vgrid_xmin_get, 1 },
	 { "Vgrid_xmin_set", _wrap_Vgrid_xmin_set, 1 },
	 { "Vgrid_hzed_get", _wrap_Vgrid_hzed_get, 1 },
	 { "Vgrid_hzed_set", _wrap_Vgrid_hzed_set, 1 },
	 { "Vgrid_hy_get", _wrap_Vgrid_hy_get, 1 },
	 { "Vgrid_hy_set", _wrap_Vgrid_hy_set, 1 },
	 { "Vgrid_hx_get", _wrap_Vgrid_hx_get, 1 },
	 { "Vgrid_hx_set", _wrap_Vgrid_hx_set, 1 },
	 { "Vgrid_nz_get", _wrap_Vgrid_nz_get, 1 },
	 { "Vgrid_nz_set", _wrap_Vgrid_nz_set, 1 },
	 { "Vgrid_ny_get", _wrap_Vgrid_ny_get, 1 },
	 { "Vgrid_ny_set", _wrap_Vgrid_ny_set, 1 },
	 { "Vgrid_nx_get", _wrap_Vgrid_nx_get, 1 },
	 { "Vgrid_nx_set", _wrap_Vgrid_nx_set, 1 },
	 { "delete_Vgrid", _wrap_delete_Vgrid, 1 },
	 { "new_Vgrid", _wrap_new_Vgrid, 1 },
	 { "startVio", _wrap_startVio, 1 },
	 { "Vgrid_readDX", _wrap_Vgrid_readDX, 1 },
	 { "Vgrid_writeDX", _wrap_Vgrid_writeDX, 1 },
	 { "Vgrid_writeUHBD", _wrap_Vgrid_writeUHBD, 1 },
	 { "Vgrid_gradient", _wrap_Vgrid_gradient, 1 },
	 { "Vgrid_curvature", _wrap_Vgrid_curvature, 1 },
	 { "Vgrid_dtor2", _wrap_Vgrid_dtor2, 1 },
	 { "Vgrid_dtor", _wrap_Vgrid_dtor, 1 },
	 { "Vgrid_value", _wrap_Vgrid_value, 1 },
	 { "Vgrid_ctor2", _wrap_Vgrid_ctor2, 1 },
	 { "Vgrid_ctor", _wrap_Vgrid_ctor, 1 },
	 { "delVgrid", _wrap_delVgrid, 1 },
	 { "set_entry", _wrap_set_entry, 1 },
	 { "get_entry", _wrap_get_entry, 1 },
	 { "double_array", _wrap_double_array, 1 },
	 { "null_array", _wrap_null_array, 1 },
	 { "ptrmap", _wrap_ptrmap, 1 },
	 { "ptradd", _wrap_ptradd, 1 },
	 { "ptrfree", _wrap_ptrfree, 1 },
	 { "ptrcreate", _wrap_ptrcreate, 1 },
	 { "ptrset", _wrap_ptrset, 1 },
	 { "ptrvalue", _wrap_ptrvalue, 1 },
	 { "ptrcast", _wrap_ptrcast, 1 },
	 { NULL, NULL }
};
static PyObject *SWIG_globals;
#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT(void,initvgridc)() {
	 PyObject *m, *d;
	 SWIG_globals = SWIG_newvarlink();
	 m = Py_InitModule("vgridc", vgridcMethods);
	 d = PyModule_GetDict(m);
/*
 * These are the pointer type-equivalency mappings. 
 * (Used by the SWIG pointer type-checker).
 */
	 SWIG_RegisterMapping("_signed_long","_long",0);
	 SWIG_RegisterMapping("_long","_unsigned_long",0);
	 SWIG_RegisterMapping("_long","_signed_long",0);
	 SWIG_RegisterMapping("_unsigned_long","_long",0);
	 SWIG_RegisterMapping("_signed_int","_int",0);
	 SWIG_RegisterMapping("_unsigned_short","_short",0);
	 SWIG_RegisterMapping("_signed_short","_short",0);
	 SWIG_RegisterMapping("_unsigned_int","_int",0);
	 SWIG_RegisterMapping("_short","_unsigned_short",0);
	 SWIG_RegisterMapping("_short","_signed_short",0);
	 SWIG_RegisterMapping("_int","_unsigned_int",0);
	 SWIG_RegisterMapping("_int","_signed_int",0);
}
