language: cpp

os:
    - osx
    - linux

compiler:
    - gcc
    - clang

env:
    - TEST=
branches:
    only:
        - master

before_script:
    - cd apbs
    - mkdir travis
    - cd travis
    - cmake -DBUILD_DOC=OFF ..

script:
    - make

after_success:
    - cd ../tests
    - PATH=$PATH:$TRAVIS_BUILD_DIR/apbs/travis/bin ./apbs_tester.py

notifications:
  slack: electrostatics:U4cSeRAFGXl9vUqdg4WOubnc
