language: cpp

os:
    - osx
    - linux
    
compiler:
    - gcc
    - clang

branches:
    only:
        - master

before_script:
    - cd apbs
    - mkdir travis
    - cd travis
    - cmake -DENABLE_FETK=OFF -DBUILD_SHARED_LIBS=OFF -DENABLE_BEM=OFF ..

script:
    - make

notifications:
  slack: electrostatics:U4cSeRAFGXl9vUqdg4WOubnc
