language: cpp

os:
    - osx
    - linux

compiler:
    - gcc
    - clang

sudo: required
dist: trusty

env:
    - FETK=ON   TEST_SUITE=fem

    - FETK=OFF  TEST_SUITE=actin-dimer-auto
    - FETK=OFF  TEST_SUITE=actin-dimer-parallel
    - FETK=OFF  TEST_SUITE=alkanes
    - FETK=OFF  TEST_SUITE=born
    - FETK=OFF  TEST_SUITE=FKBP
    - FETK=OFF  TEST_SUITE=geoflow
    - FETK=OFF  TEST_SUITE=hca-bind
    - FETK=OFF  TEST_SUITE=ion-pmf
    - FETK=OFF  TEST_SUITE=ion-protein
    - FETK=OFF  TEST_SUITE=ionize
    - FETK=OFF  TEST_SUITE=pka-lig
    - FETK=OFF  TEST_SUITE=point-pmf
    - FETK=OFF  TEST_SUITE=solv
    - FETK=OFF  TEST_SUITE=protein-rna

branches:
    only:
        - master

before_script:
    - cd apbs
    - mkdir travis
    - cd travis
    - cmake -DENABLE_GEOFLOW=ON -DBUILD_DOC=OFF -DENABLE_FETK=$FETK ..

script:
    - make VERBOSE=1
    - cd ../tests
    - bash run_travis_test.sh $TRAVIS_BUILD_DIR/apbs/travis/bin $TEST_SUITE

notifications:
  slack: electrostatics:U4cSeRAFGXl9vUqdg4WOubnc
