language: cpp

os:
    - osx
    - linux

compiler:
    - gcc
    - clang

sudo: false

env:
    - TEST_SUITE=test_actin-dimer-auto.cfg
    - TEST_SUITE=test_actin-dimer-parallel.cfg
    - TEST_SUITE=test_alkanes.cfg
    - TEST_SUITE=test_born.cfg
    - TEST_SUITE=test_FKBP.cfg
    - TEST_SUITE=test_geoflow.cfg
    - TEST_SUITE=test_hca-bind.cfg
    - TEST_SUITE=test_ion-pmf.cfg
    - TEST_SUITE=test_ion-protein.cfg
    - TEST_SUITE=test_ionize.cfg
    - TEST_SUITE=test_pka-lig.cfg
    - TEST_SUITE=test_point-pmf.cfg
    - TEST_SUITE=test_solv.cfg

branches:
    only:
        - master

before_script:
    - cd apbs
    - mkdir travis
    - cd travis
    - cmake -DBUILD_DOC=OFF ..

script:
    - make
    - cd ../tests
    - bash run_travis_test.sh $TRAVIS_BUILD_DIR/apbs/travis/bin $TEST_SUITE

notifications:
  slack: electrostatics:U4cSeRAFGXl9vUqdg4WOubnc
