image:
  - Visual Studio 2019

clone_folder: c:\projects\source

build_script:
- cmd: >-

    git submodule init 

    git submodule update 

    mkdir build

    cd build

    cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON -DBUILD_TOOLS=ON -DCHECK_EPSILON=ON -DENABLE_BEM=ON -DENABLE_GEOFLOW=ON -DENABLE_INLINE=ON -DENABLE_PBAM=ON -DENABLE_PYTHON=ON                  -DENABLE_TESTS=ON -DENABLE_VERBOSE_DEBUG=ON -DGET_MSMS=ON -DGET_NanoShaper=ON -G "Visual Studio 16" c:\projects\source

    cmake --build . --config "Release" -- /p:PreferredToolArchitecture=x64
