#! /bin/sh -x

##############################################################################
# Purpose: Auto-generate the GNU configure script.
#
# Author:  Nathan Baker and Michael Holst
##############################################################################

rm -f config.cache
aclocal
autoconf
autoheader
automake
# libtoolize -f
# aclocal
