#! /bin/sh -x

##############################################################################
# Purpose: Auto-generate the GNU configure script.
#
# Author:  Nathan Baker and Michael Holst
##############################################################################

rm -f config.cache
#libtoolize --automake --force --copy
aclocal
autoconf
autoheader
automake
# aclocal

cd test
rm -f config.cache
#libtoolize --automake --force --copy
aclocal
autoconf
autoheader
automake
# aclocal

cd ..
