APBS: Vpmgp class
Vpmgp class
Parameter structure for Mike Holst's PMGP code.
Data Structures
struct sVpmgp
Contains public data members for Vpmgp class/module.
Files
file vpmgp.h
Contains declarations for class Vpmgp.
file vpmgp.c
Class Vpmgp methods.
Typedefs
typedef struct sVpmgp Vpmgp
Declaration of the Vpmgp class as the sVpmgp structure.
Functions
Vpmgp * Vpmgp_ctor (MGparm *mgparm)
Construct PMG parameter object and initialize to default values.
int Vpmgp_ctor2 (Vpmgp *thee, MGparm *mgparm)
FORTRAN stub to construct PMG parameter object and initialize to default values.
void Vpmgp_dtor (Vpmgp **thee)
Object destructor.
void Vpmgp_dtor2 (Vpmgp *thee)
FORTRAN stub for object destructor.
Detailed Description
Parameter structure for Mike Holst's PMGP code.
Note:
Variables and many default values taken directly from PMG
Function Documentation
Vpmgp* Vpmgp_ctor (MGparm * mgparm)
Construct PMG parameter object and initialize to default values.
Author:
Nathan Baker
Parameters:
mgparm MGParm object containing parameters to be used in setup
Returns:
Newly allocated and initialized Vpmgp object
Referenced by initMG().
int Vpmgp_ctor2 (Vpmgp * thee, MGparm * mgparm)
FORTRAN stub to construct PMG parameter object and initialize to default values.
Author:
Nathan Baker
Parameters:
thee Newly allocated PMG object
mgparm MGParm object containing parameters to be used in setup
Returns:
1 if successful, 0 otherwise
void Vpmgp_dtor (Vpmgp ** thee)
Object destructor.
Author:
Nathan Baker
Parameters:
thee Pointer to memory location for Vpmgp object
Referenced by initMG(), and killMG().
void Vpmgp_dtor2 (Vpmgp * thee)
FORTRAN stub for object destructor.
Author:
Nathan Baker
Parameters:
thee Pointer to Vpmgp object