APBS: Valist class
Valist class
Container class for list of atom objects.
Data Structures
struct sValist
Container class for list of atom objects.
Files
file valist.h
Contains declarations for class Valist.
Typedefs
typedef struct sValist Valist
Declaration of the Valist class as the Valist structure.
Functions
Vatom * Valist_getAtomList (Valist *thee)
Get actual array of atom objects from the list.
double Valist_getCenterX (Valist *thee)
Get x-coordinate of molecule center.
double Valist_getCenterY (Valist *thee)
Get y-coordinate of molecule center.
double Valist_getCenterZ (Valist *thee)
Get z-coordinate of molecule center.
int Valist_getNumberAtoms (Valist *thee)
Get number of atoms in the list.
Vatom * Valist_getAtom (Valist *thee, int i)
Get pointer to particular atom in list.
unsigned long int Valist_memChk (Valist *thee)
Get total memory allocated for this object and its members.
Valist * Valist_ctor ()
Construct the atom list object.
Vrc_Codes Valist_ctor2 (Valist *thee)
FORTRAN stub to construct the atom list object.
void Valist_dtor (Valist **thee)
Destroys atom list object.
void Valist_dtor2 (Valist *thee)
FORTRAN stub to destroy atom list object.
Vrc_Codes Valist_readPQR (Valist *thee, Vparam *param, Vio *sock)
Fill atom list with information from a PQR file.
Vrc_Codes Valist_readPDB (Valist *thee, Vparam *param, Vio *sock)
Fill atom list with information from a PDB file.
Vrc_Codes Valist_readXML (Valist *thee, Vparam *param, Vio *sock)
Fill atom list with information from an XML file.
Vrc_Codes Valist_getStatistics (Valist *thee)
Load up Valist with various statistics.
Detailed Description
Container class for list of atom objects.
Function Documentation
Valist* Valist_ctor ()
Construct the atom list object.
Author:
Nathan Baker
Returns:
Pointer to newly allocated (empty) atom list
References Valist_ctor2(), and VRC_SUCCESS.
Referenced by loadMolecules().
Vrc_Codes Valist_ctor2 (Valist * thee)
FORTRAN stub to construct the atom list object.
Author:
Nathan Baker, Yong Huang
Returns:
Success enumeration
Parameters:
thee Storage for new atom list
References sValist::atoms, sValist::number, sValist::vmem, and VRC_SUCCESS.
Referenced by Valist_ctor().
void Valist_dtor (Valist ** thee)
Destroys atom list object.
Author:
Nathan Baker
Parameters:
thee Pointer to storage for atom list
References Valist_dtor2().
Referenced by killMolecules(), and loadMolecules().
void Valist_dtor2 (Valist * thee)
FORTRAN stub to destroy atom list object.
Author:
Nathan Baker
Parameters:
thee Pointer to atom list object
References sValist::atoms, sValist::number, and sValist::vmem.
Referenced by Valist_dtor().
Vatom* Valist_getAtom (Valist * thee, int i)
Get pointer to particular atom in list.
Author:
Nathan Baker
Returns:
Pointer to atom object i
Parameters:
thee Atom list object
i Index of atom in list
References sValist::atoms, and sValist::number.
Referenced by energyMG(), extEnergy(), fillcoChargeSpline1(), fillcoChargeSpline2(), fillcoCoefMolDielNoSmooth(), fillcoCoefMolIon(), fillcoCoefSpline(), fillcoCoefSpline3(), fillcoCoefSpline4(), fillcoPermanentMultipole(), forceAPOL(), initAPOL(), initMG(), qfForceSpline1(), qfForceSpline2(), qfForceSpline4(), storeAtomEnergy(), Vacc_SASA(), Vacc_storeParms(), Vcsm_getAtom(), Vcsm_init(), Vcsm_update(), Vfetk_getAtomColor(), Vfetk_setAtomColors(), Vgreen_coulomb_direct(), Vgreen_coulombD_direct(), Vpbe_ctor2(), Vpbe_getCoulombEnergy1(), Vpmg_dbForce(), Vpmg_ibForce(), Vpmg_polarizEnergy(), Vpmg_qfEnergyPoint(), Vpmg_setPart(), and Vpmg_unsetPart().
Vatom* Valist_getAtomList (Valist * thee)
Get actual array of atom objects from the list.
Author:
Nathan Baker
Returns:
Array of atom objects
Parameters:
thee Atom list object
References sValist::atoms.
double Valist_getCenterX (Valist * thee)
Get x-coordinate of molecule center.
Author:
Nathan Baker
Returns:
X-coordinate of molecule center
Parameters:
thee Atom list object
References sValist::center.
double Valist_getCenterY (Valist * thee)
Get y-coordinate of molecule center.
Author:
Nathan Baker
Returns:
Y-coordinate of molecule center
Parameters:
thee Atom list object
References sValist::center.
double Valist_getCenterZ (Valist * thee)
Get z-coordinate of molecule center.
Author:
Nathan Baker
Returns:
Z-coordinate of molecule center
Parameters:
thee Atom list object
References sValist::center.
int Valist_getNumberAtoms (Valist * thee)
Get number of atoms in the list.
Author:
Nathan Baker
Returns:
Number of atoms in list
Parameters:
thee Atom list object
References sValist::number.
Referenced by energyMG(), extEnergy(), fillcoChargeSpline1(), fillcoChargeSpline2(), fillcoCoefMolDielNoSmooth(), fillcoCoefMolIon(), fillcoCoefSpline(), fillcoCoefSpline3(), fillcoCoefSpline4(), fillcoPermanentMultipole(), forceAPOL(), forceMG(), initAPOL(), initMG(), loadMolecules(), storeAtomEnergy(), Vacc_allocate(), Vacc_dtor2(), Vacc_SASA(), Vacc_storeParms(), Vacc_wcaEnergy(), Vcsm_init(), Vfetk_getAtomColor(), Vfetk_qfEnergy(), Vfetk_setAtomColors(), Vgreen_coulomb(), Vgreen_coulomb_direct(), Vgreen_coulombD(), Vgreen_coulombD_direct(), Vpbe_ctor2(), Vpbe_getCoulombEnergy1(), Vpmg_polarizEnergy(), Vpmg_qfEnergyPoint(), Vpmg_setPart(), and Vpmg_unsetPart().
Vrc_Codes Valist_getStatistics (Valist * thee)
Load up Valist with various statistics.
Author:
Nathan Baker, Yong Huang
Returns:
Success enumeration
References sValist::atoms, sValist::center, sVatom::charge, sValist::charge, sValist::maxcrd, sValist::maxrad, sValist::mincrd, sValist::number, sVatom::position, sVatom::radius, VRC_FAILURE, and VRC_SUCCESS.
Referenced by Valist_readPDB(), Valist_readPQR(), and Valist_readXML().
unsigned long int Valist_memChk (Valist * thee)
Get total memory allocated for this object and its members.
Author:
Nathan Baker
Returns:
Total memory in bytes
Parameters:
thee Atom list object
References sValist::vmem.
Vrc_Codes Valist_readPDB (Valist * thee, Vparam * param, Vio * sock)
Fill atom list with information from a PDB file.
Author:
Nathan Baker, Todd Dolinsky, Yong Huang
Returns:
Success enumeration
Note:
We don't actually respect PDB format; instead recognize whitespace- or tab-delimited fields which allows us to deal with structures with coordinates > 999 or < -999.
Parameters:
thee Atom list object
param A pre-initialized parameter object
sock Socket read for reading PDB file
References sVparam_AtomData::charge, sVparam_AtomData::epsilon, sValist::number, sVparam_AtomData::radius, Valist_getStatistics(), Vatom_setAtomID(), Vatom_setAtomName(), Vatom_setCharge(), Vatom_setEpsilon(), Vatom_setPosition(), Vatom_setRadius(), Vatom_setResName(), sValist::vmem, Vparam_getAtomData(), VRC_FAILURE, and Vstring_strcasecmp().
Referenced by loadMolecules().
Vrc_Codes Valist_readPQR (Valist * thee, Vparam * param, Vio * sock)
Fill atom list with information from a PQR file.
Author:
Nathan Baker, Yong Huang
Returns:
Success enumeration
Note:
A PQR file has PDB structure with charge and radius in the last two columns instead of weight and occupancy
We don't actually respect PDB format; instead recognize whitespace- or tab-delimited fields which allows us to deal with structures with coordinates > 999 or < -999.
Parameters:
thee Atom list object
param A pre-initialized parameter object
sock Socket reading for reading PQR file
References sVparam_AtomData::charge, sVparam_AtomData::epsilon, sValist::number, sVparam_AtomData::radius, Valist_getStatistics(), Vatom_setAtomID(), Vatom_setAtomName(), Vatom_setCharge(), Vatom_setEpsilon(), Vatom_setPosition(), Vatom_setRadius(), Vatom_setResName(), sValist::vmem, Vparam_getAtomData(), VRC_FAILURE, and Vstring_strcasecmp().
Referenced by loadMolecules().
Vrc_Codes Valist_readXML (Valist * thee, Vparam * param, Vio * sock)
Fill atom list with information from an XML file.
Author:
Todd Dolinsky, Yong Huang
Returns:
Success enumeration
Note:
The XML file must adhere to some guidelines, notably the presence of an <atom> tag with all other useful information (x, y, z, charge, and radius) as nested elements.
Parameters:
thee Atom list object
param A pre-initialized parameter object
sock Socket reading for reading PQR file
References sValist::number, Valist_getStatistics(), Vatom_setAtomID(), Vatom_setCharge(), Vatom_setPosition(), Vatom_setRadius(), sValist::vmem, VRC_FAILURE, and Vstring_strcasecmp().
Referenced by loadMolecules().