APBS: FEMparm class
FEMparm class
Parameter structure for FEM-specific variables from input files.
Data Structures
struct sFEMparm
Parameter structure for FEM-specific variables from input files.
Files
file femparm.h
Contains declarations for class APOLparm.
file femparm.c
Class FEMparm methods.
Typedefs
typedef enum eFEMparm_EtolType FEMparm_EtolType
Declare FEparm_EtolType type.
typedef enum eFEMparm_EstType FEMparm_EstType
Declare FEMparm_EstType type.
typedef enum eFEMparm_CalcType FEMparm_CalcType
Declare FEMparm_CalcType type.
typedef struct sFEMparm FEMparm
Declaration of the FEMparm class as the FEMparm structure.
Enumerations
enum eFEMparm_EtolType {
FET_SIMP = 0,
FET_GLOB = 1,
FET_FRAC = 2
}
Adaptive refinment error estimate tolerance key.
enum eFEMparm_EstType {
FRT_UNIF = 0,
FRT_GEOM = 1,
FRT_RESI = 2,
FRT_DUAL = 3,
FRT_LOCA = 4
}
Adaptive refinment error estimator method.
enum eFEMparm_CalcType {
FCT_MANUAL,
FCT_NONE
}
Calculation type.
Functions
FEMparm * FEMparm_ctor (FEMparm_CalcType type)
Construct FEMparm.
int FEMparm_ctor2 (FEMparm *thee, FEMparm_CalcType type)
FORTRAN stub to construct FEMparm.
void FEMparm_dtor (FEMparm **thee)
Object destructor.
void FEMparm_dtor2 (FEMparm *thee)
FORTRAN stub for object destructor.
int FEMparm_check (FEMparm *thee)
Consistency check for parameter values stored in object.
void FEMparm_copy (FEMparm *thee, FEMparm *source)
Copy target object into thee.
Detailed Description
Parameter structure for FEM-specific variables from input files.
Typedef Documentation
typedef enum eFEMparm_EtolType FEMparm_EtolType
Declare FEparm_EtolType type.
Author:
Nathan Baker
Enumeration Type Documentation
enum eFEMparm_CalcType
Calculation type.
Enumerator:
FCT_MANUAL fe-manual
FCT_NONE unspecified
enum eFEMparm_EstType
Adaptive refinment error estimator method.
Note:
Do not change these values; they correspond to settings in FEtk
Author:
Nathan Baker
Enumerator:
FRT_UNIF Uniform refinement
FRT_GEOM Geometry-based (i.e. surfaces and charges) refinement
FRT_RESI Nonlinear residual estimate-based refinement
FRT_DUAL Dual-solution weight nonlinear residual estimate-based refinement
FRT_LOCA Local problem error estimate-based refinement
enum eFEMparm_EtolType
Adaptive refinment error estimate tolerance key.
Author:
Nathan Baker
Enumerator:
FET_SIMP per-simplex error tolerance
FET_GLOB global error tolerance
FET_FRAC fraction of simplices we want to have refined
Function Documentation
int FEMparm_check (FEMparm * thee)
Consistency check for parameter values stored in object.
Author:
Nathan Baker
Parameters:
thee FEMparm object
Returns:
1 if OK, 0 otherwise
References sFEMparm::parsed, sFEMparm::setakeyPRE, sFEMparm::setakeySOLVE, sFEMparm::setekey, sFEMparm::setetol, sFEMparm::setglen, sFEMparm::setmaxsolve, sFEMparm::setmaxvert, sFEMparm::settargetNum, sFEMparm::settargetRes, and sFEMparm::settype.
void FEMparm_copy (FEMparm * thee, FEMparm * source)
Copy target object into thee.
Author:
Nathan Baker
Parameters:
thee Destination object
source Source object
References sFEMparm::akeyPRE, sFEMparm::akeySOLVE, sFEMparm::ekey, sFEMparm::etol, sFEMparm::glen, sFEMparm::maxsolve, sFEMparm::maxvert, sFEMparm::meshID, sFEMparm::parsed, sFEMparm::pkey, sFEMparm::setakeyPRE, sFEMparm::setakeySOLVE, sFEMparm::setekey, sFEMparm::setetol, sFEMparm::setglen, sFEMparm::setmaxsolve, sFEMparm::setmaxvert, sFEMparm::settargetNum, sFEMparm::settargetRes, sFEMparm::settype, sFEMparm::targetNum, sFEMparm::targetRes, sFEMparm::type, and sFEMparm::useMesh.
Referenced by NOsh_calc_copy().
FEMparm* FEMparm_ctor (FEMparm_CalcType type)
Construct FEMparm.
Author:
Nathan Baker
Parameters:
type FEM calculation type
Returns:
Newly allocated and initialized Vpmgp object
References FEMparm_ctor2().
Referenced by NOsh_calc_ctor().
int FEMparm_ctor2 (FEMparm * thee, FEMparm_CalcType type)
FORTRAN stub to construct FEMparm.
Author:
Nathan Baker
Parameters:
thee Pointer to allocated FEMparm object
type FEM calculation type
Returns:
1 if successful, 0 otherwise
References sFEMparm::parsed, sFEMparm::setakeyPRE, sFEMparm::setakeySOLVE, sFEMparm::setekey, sFEMparm::setetol, sFEMparm::setglen, sFEMparm::setmaxsolve, sFEMparm::setmaxvert, sFEMparm::settargetNum, sFEMparm::settargetRes, sFEMparm::settype, sFEMparm::type, and sFEMparm::useMesh.
Referenced by FEMparm_ctor().
void FEMparm_dtor (FEMparm ** thee)
Object destructor.
Author:
Nathan Baker
Parameters:
thee Pointer to memory location of FEMparm object
References FEMparm_dtor2().
Referenced by NOsh_calc_dtor().
void FEMparm_dtor2 (FEMparm * thee)
FORTRAN stub for object destructor.
Author:
Nathan Baker
Parameters:
thee Pointer to FEMparm object
Referenced by FEMparm_dtor().