APBS: Vstring class
Vstring class
Provides a collection of useful non-ANSI string functions.
Files
file vstring.h
Contains declarations for class Vstring.
Functions
int Vstring_strcasecmp (const char *s1, const char *s2)
Case-insensitive string comparison (BSD standard).
int Vstring_isdigit (const char *tok)
A modified sscanf that examines the complete string.
Detailed Description
Provides a collection of useful non-ANSI string functions.
Function Documentation
int Vstring_isdigit (const char * tok)
A modified sscanf that examines the complete string.
Author:
Todd Dolinsky
Parameters:
tok The string to examine
Returns:
1 if the entire string is an integer, 0 if otherwise.
int Vstring_strcasecmp (const char * s1, const char * s2)
Case-insensitive string comparison (BSD standard).
Author:
Copyright (c) 1988-1993 The Regents of the University of California. Copyright (c) 1995-1996 Sun Microsystems, Inc.
Note:
Copyright (c) 1988-1993 The Regents of the University of California. Copyright (c) 1995-1996 Sun Microsystems, Inc.
Parameters:
s1 First string for comparison
s2 Second string for comparison
Returns:
An integer less than, equal to, or greater than zero if s1 is found, respectively, to be less than, to match, or be greater than s2. (Source: Linux man pages)
Referenced by APOLparm_parseToken(), FEMparm_parseToken(), main(), MGparm_parseToken(), NOsh_parseInput(), PBEparm_parseToken(), printApolEnergy(), printApolForce(), printElecEnergy(), printElecForce(), printEnergy(), printForce(), readXMLFileAtom(), Valist_readPDB(), Valist_readPQR(), Valist_readXML(), Vparam_getAtomData(), Vparam_getResData(), Vparam_readFlatFile(), Vparam_readXMLFile(), writedataFlat(), and writedataXML().