APBS: Vclist class
Vclist class
Atom cell list.
Data Structures
struct sVclistCell
Atom cell list cell.
struct sVclist
Atom cell list.
Files
file vclist.h
Contains declarations for class Vclist.
file vclist.c
Class Vclist methods.
Typedefs
typedef struct sVclistCell VclistCell
Declaration of the VclistCell class as the VclistCell structure.
typedef struct sVclist Vclist
Declaration of the Vclist class as the Vclist structure.
typedef enum eVclist_DomainMode Vclist_DomainMode
Declaration of Vclist_DomainMode enumeration type.
Enumerations
enum eVclist_DomainMode {
CLIST_AUTO_DOMAIN,
CLIST_MANUAL_DOMAIN
}
Atom cell list domain setup mode.
Functions
unsigned long int Vclist_memChk (Vclist *thee)
Get number of bytes in this object and its members.
double Vclist_maxRadius (Vclist *thee)
Get the max probe radius value (in A) the cell list was constructed with.
Vclist * Vclist_ctor (Valist *alist, double max_radius, int npts[VAPBS_DIM], Vclist_DomainMode mode, double lower_corner[VAPBS_DIM], double upper_corner[VAPBS_DIM])
Construct the cell list object.
Vrc_Codes Vclist_ctor2 (Vclist *thee, Valist *alist, double max_radius, int npts[VAPBS_DIM], Vclist_DomainMode mode, double lower_corner[VAPBS_DIM], double upper_corner[VAPBS_DIM])
FORTRAN stub to construct the cell list object.
void Vclist_dtor (Vclist **thee)
Destroy object.
void Vclist_dtor2 (Vclist *thee)
FORTRAN stub to destroy object.
VclistCell * Vclist_getCell (Vclist *thee, double position[VAPBS_DIM])
Return cell corresponding to specified position or return VNULL.
VclistCell * VclistCell_ctor (int natoms)
Allocate and construct a cell list cell object.
Vrc_Codes VclistCell_ctor2 (VclistCell *thee, int natoms)
Construct a cell list object.
void VclistCell_dtor (VclistCell **thee)
Destroy object.
void VclistCell_dtor2 (VclistCell *thee)
FORTRAN stub to destroy object.
Detailed Description
Atom cell list.
Enumeration Type Documentation
enum eVclist_DomainMode
Atom cell list domain setup mode.
Author:
Nathan Baker
Enumerator:
CLIST_AUTO_DOMAIN
Setup the cell list domain automatically to encompass the entire molecule
CLIST_MANUAL_DOMAIN
Specify the cell list domain manually through the constructor
Function Documentation
Vclist* Vclist_ctor (Valist * alist, double max_radius, int npts[VAPBS_DIM], Vclist_DomainMode mode, double lower_corner[VAPBS_DIM], double upper_corner[VAPBS_DIM])
Construct the cell list object.
Author:
Nathan Baker
Returns:
Newly allocated Vclist object
Parameters:
max_radius Molecule for cell list queries
npts Max probe radius (Å) to be queried
mode Number of in hash table points in each direction
lower_corner Mode to construct table
upper_corner Hash table lower corner for manual construction (see mode variable); ignored otherwise Hash table upper corner for manual construction (see mode variable); ignored otherwise
References Vclist_ctor2(), and VRC_SUCCESS.
Referenced by initAPOL(), and Vpbe_ctor2().
Vrc_Codes Vclist_ctor2 (Vclist * thee, Valist * alist, double max_radius, int npts[VAPBS_DIM], Vclist_DomainMode mode, double lower_corner[VAPBS_DIM], double upper_corner[VAPBS_DIM])
FORTRAN stub to construct the cell list object.
Author:
Nathan Baker, Yong Huang
Returns:
Success enumeration
Parameters:
alist Memory for Vclist objet
max_radius Molecule for cell list queries
npts Max probe radius (Å) to be queried
mode Number of in hash table points in each direction
lower_corner Mode to construct table
upper_corner Hash table lower corner for manual construction (see mode variable); ignored otherwise Hash table upper corner for manual construction (see mode variable); ignored otherwise
References sVclist::cells, sVclist::n, sVclistCell::natoms, sVclist::vmem, VRC_FAILURE, and VRC_SUCCESS.
Referenced by Vclist_ctor().
void Vclist_dtor (Vclist ** thee)
Destroy object.
Author:
Nathan Baker
Parameters:
thee Pointer to memory location of object
References Vclist_dtor2().
Referenced by initAPOL(), and Vpbe_dtor2().
void Vclist_dtor2 (Vclist * thee)
FORTRAN stub to destroy object.
Author:
Nathan Baker
Parameters:
thee Pointer to object
References sVclist::cells, sVclist::n, VclistCell_dtor2(), and sVclist::vmem.
Referenced by Vclist_dtor().
VclistCell* Vclist_getCell (Vclist * thee, double position[VAPBS_DIM])
Return cell corresponding to specified position or return VNULL.
Author:
Nathan Baker
Returns:
Pointer to VclistCell object or VNULL if no cell available (away from molecule).
Parameters:
position Pointer to Vclist cell list Position to evaluate
References sVclist::cells, sVclist::lower_corner, sVclist::npts, and sVclist::spacs.
Referenced by ivdwAccExclus(), Vacc_fastMolAcc(), Vacc_splineAcc(), and Vacc_splineAccGrad().
double Vclist_maxRadius (Vclist * thee)
Get the max probe radius value (in A) the cell list was constructed with.
Author:
Nathan Baker
Returns:
Max probe radius (in A)
Parameters:
thee Cell list object
References sVclist::max_radius.
Referenced by ivdwAccExclus(), Vacc_splineAcc(), Vacc_splineAccGrad(), and Vacc_storeParms().
unsigned long int Vclist_memChk (Vclist * thee)
Get number of bytes in this object and its members.
Author:
Nathan Baker
Returns:
Number of bytes allocated for object
Parameters:
thee Object for memory check
References sVclist::vmem.
VclistCell* VclistCell_ctor (int natoms)
Allocate and construct a cell list cell object.
Author:
Nathan Baker
Returns:
Pointer to newly-allocated and constructed object.
Parameters:
natoms Number of atoms associated with this cell
References VclistCell_ctor2(), and VRC_SUCCESS.
Vrc_Codes VclistCell_ctor2 (VclistCell * thee, int natoms)
Construct a cell list object.
Author:
Nathan Baker, Yong Huang
Returns:
Success enumeration
Parameters:
natoms Memory location for object Number of atoms associated with this cell
References sVclistCell::atoms, sVclistCell::natoms, VRC_FAILURE, and VRC_SUCCESS.
Referenced by VclistCell_ctor().
void VclistCell_dtor (VclistCell ** thee)
Destroy object.
Author:
Nathan Baker
Parameters:
thee Pointer to memory location of object
References VclistCell_dtor2().
void VclistCell_dtor2 (VclistCell * thee)
FORTRAN stub to destroy object.
Author:
Nathan Baker
Parameters:
thee Pointer to object
References sVclistCell::atoms, and sVclistCell::natoms.
Referenced by Vclist_dtor2(), and VclistCell_dtor().