APBS: APOLparm class
APOLparm class
Parameter structure for APOL-specific variables from input files.
Data Structures
struct sAPOLparm
Parameter structure for APOL-specific variables from input files.
Files
file femparm.h
Contains declarations for class APOLparm.
file apolparm.c
Class APOLparm methods.
Typedefs
typedef enum eAPOLparm_calcEnergy APOLparm_calcEnergy
Define eAPOLparm_calcEnergy enumeration as APOLparm_calcEnergy.
typedef enum eAPOLparm_calcForce APOLparm_calcForce
Define eAPOLparm_calcForce enumeration as APOLparm_calcForce.
typedef enum eAPOLparm_doCalc APOLparm_doCalc
Define eAPOLparm_calcForce enumeration as APOLparm_calcForce.
typedef struct sAPOLparm APOLparm
Declaration of the APOLparm class as the APOLparm structure.
Enumerations
enum eAPOLparm_calcEnergy {
ACE_NO = 0,
ACE_TOTAL = 1,
ACE_COMPS = 2
}
Define energy calculation enumeration.
enum eAPOLparm_calcForce {
ACF_NO = 0,
ACF_TOTAL = 1,
ACF_COMPS = 2
}
Define force calculation enumeration.
enum eAPOLparm_doCalc {
ACD_NO = 0,
ACD_YES = 1,
ACD_ERROR = 2
}
Define force calculation enumeration.
Functions
APOLparm * APOLparm_ctor ()
Construct APOLparm.
Vrc_Codes APOLparm_ctor2 (APOLparm *thee)
FORTRAN stub to construct APOLparm.
void APOLparm_dtor (APOLparm **thee)
Object destructor.
void APOLparm_dtor2 (APOLparm *thee)
FORTRAN stub for object destructor.
Vrc_Codes APOLparm_check (APOLparm *thee)
Consistency check for parameter values stored in object.
void APOLparm_copy (APOLparm *thee, APOLparm *source)
Copy target object into thee.
Detailed Description
Parameter structure for APOL-specific variables from input files.
Enumeration Type Documentation
enum eAPOLparm_calcEnergy
Define energy calculation enumeration.
Enumerator:
ACE_NO Do not perform energy calculation
ACE_TOTAL Calculate total energy only
ACE_COMPS Calculate per-atom energy components
enum eAPOLparm_calcForce
Define force calculation enumeration.
Enumerator:
ACF_NO Do not perform force calculation
ACF_TOTAL Calculate total force only
ACF_COMPS Calculate per-atom force components
enum eAPOLparm_doCalc
Define force calculation enumeration.
Enumerator:
ACD_NO Do not perform calculation
ACD_YES Perform calculations
ACD_ERROR Error setting up calculation
Function Documentation
Vrc_Codes APOLparm_check (APOLparm * thee)
Consistency check for parameter values stored in object.
Author:
David Gohara, Yong Huang
Parameters:
thee APOLparm object
Returns:
Success enumeration
References sAPOLparm::parsed, sAPOLparm::setbconc, sAPOLparm::setdpos, sAPOLparm::setgamma, sAPOLparm::setgrid, sAPOLparm::setmolid, sAPOLparm::setpress, sAPOLparm::setsdens, sAPOLparm::setsrad, sAPOLparm::setsrfm, sAPOLparm::setswin, sAPOLparm::settemp, VRC_FAILURE, and VRC_SUCCESS.
void APOLparm_copy (APOLparm * thee, APOLparm * source)
Copy target object into thee.
Author:
Nathan Baker
Parameters:
thee Destination object
source Source object
References sAPOLparm::bconc, sAPOLparm::calcenergy, sAPOLparm::calcforce, sAPOLparm::dpos, sAPOLparm::gamma, sAPOLparm::grid, sAPOLparm::molid, sAPOLparm::parsed, sAPOLparm::press, sAPOLparm::sasa, sAPOLparm::sav, sAPOLparm::sdens, sAPOLparm::setbconc, sAPOLparm::setcalcenergy, sAPOLparm::setcalcforce, sAPOLparm::setdpos, sAPOLparm::setgamma, sAPOLparm::setgrid, sAPOLparm::setmolid, sAPOLparm::setpress, sAPOLparm::setsdens, sAPOLparm::setsrad, sAPOLparm::setsrfm, sAPOLparm::setswin, sAPOLparm::settemp, sAPOLparm::setwat, sAPOLparm::srad, sAPOLparm::srfm, sAPOLparm::swin, sAPOLparm::temp, sAPOLparm::totForce, and sAPOLparm::wcaEnergy.
Referenced by NOsh_calc_copy().
APOLparm* APOLparm_ctor ()
Construct APOLparm.
Author:
David Gohara
Returns:
Newly allocated and initialized Vpmgp object
References APOLparm_ctor2(), and VRC_SUCCESS.
Referenced by NOsh_calc_ctor().
Vrc_Codes APOLparm_ctor2 (APOLparm * thee)
FORTRAN stub to construct APOLparm.
Author:
David Gohara, Yong Huang
Parameters:
thee Pointer to allocated APOLparm object
Returns:
Success enumeration
References sAPOLparm::parsed, sAPOLparm::sasa, sAPOLparm::sav, sAPOLparm::setbconc, sAPOLparm::setdpos, sAPOLparm::setgamma, sAPOLparm::setgrid, sAPOLparm::setmolid, sAPOLparm::setpress, sAPOLparm::setsdens, sAPOLparm::setsrad, sAPOLparm::setsrfm, sAPOLparm::setswin, sAPOLparm::settemp, sAPOLparm::setwat, sAPOLparm::totForce, VRC_FAILURE, VRC_SUCCESS, and sAPOLparm::wcaEnergy.
Referenced by APOLparm_ctor().
void APOLparm_dtor (APOLparm ** thee)
Object destructor.
Author:
David Gohara
Parameters:
thee Pointer to memory location of APOLparm object
References APOLparm_dtor2().
Referenced by NOsh_calc_dtor().
void APOLparm_dtor2 (APOLparm * thee)
FORTRAN stub for object destructor.
Author:
David Gohara
Parameters:
thee Pointer to APOLparm object
Referenced by APOLparm_dtor().