APBS: Vatom class
Vatom class
Atom class for interfacing APBS with PDB files.
Data Structures
struct sVatom
Contains public data members for Vatom class/module.
Files
file vatom.h
Contains declarations for class Vatom.
file vatom.c
Class Vatom methods.
Typedefs
typedef struct sVatom Vatom
Declaration of the Vatom class as the Vatom structure.
Functions
double * Vatom_getPosition (Vatom *thee)
Get atomic position.
void Vatom_setRadius (Vatom *thee, double radius)
Set atomic radius.
double Vatom_getRadius (Vatom *thee)
Get atomic position.
void Vatom_setPartID (Vatom *thee, int partID)
Set partition ID.
double Vatom_getPartID (Vatom *thee)
Get partition ID.
void Vatom_setAtomID (Vatom *thee, int id)
Set atom ID.
double Vatom_getAtomID (Vatom *thee)
Get atom ID.
void Vatom_setCharge (Vatom *thee, double charge)
Set atomic charge.
double Vatom_getCharge (Vatom *thee)
Get atomic charge.
void Vatom_setEpsilon (Vatom *thee, double epsilon)
Set atomic epsilon.
double Vatom_getEpsilon (Vatom *thee)
Get atomic epsilon.
unsigned long int Vatom_memChk (Vatom *thee)
Return the memory used by this structure (and its contents) in bytes.
void Vatom_setResName (Vatom *thee, char resName[VMAX_RECLEN])
Set residue name.
void Vatom_setAtomName (Vatom *thee, char atomName[VMAX_RECLEN])
Set atom name.
void Vatom_getResName (Vatom *thee, char resName[VMAX_RECLEN])
Retrieve residue name.
void Vatom_getAtomName (Vatom *thee, char atomName[VMAX_RECLEN])
Retrieve atom name.
Vatom * Vatom_ctor ()
Constructor for the Vatom class.
int Vatom_ctor2 (Vatom *thee)
FORTRAN stub constructor for the Vatom class.
void Vatom_dtor (Vatom **thee)
Object destructor.
void Vatom_dtor2 (Vatom *thee)
FORTRAN stub object destructor.
void Vatom_setPosition (Vatom *thee, double position[3])
Set the atomic position.
void Vatom_copyTo (Vatom *thee, Vatom *dest)
Copy information to another atom.
void Vatom_copyFrom (Vatom *thee, Vatom *src)
Copy information to another atom.
Detailed Description
Atom class for interfacing APBS with PDB files.
Function Documentation
void Vatom_copyFrom (Vatom * thee, Vatom * src)
Copy information to another atom.
Author:
Nathan Baker
Parameters:
thee Destination for atom information
src Source for atom information
References Vatom_copyTo().
void Vatom_copyTo (Vatom * thee, Vatom * dest)
Copy information to another atom.
Author:
Nathan Baker
Parameters:
thee Source for atom information
dest Destination for atom information
Referenced by Vatom_copyFrom().
Vatom* Vatom_ctor ()
Constructor for the Vatom class.
Author:
Nathan Baker
Returns:
Pointer to newly allocated Vatom object
References Vatom_ctor2().
int Vatom_ctor2 (Vatom * thee)
FORTRAN stub constructor for the Vatom class.
Author:
Nathan Baker
Parameters:
thee Pointer to Vatom allocated memory location
Returns:
1 if succesful, 0 otherwise
References sVatom::partID.
Referenced by Vatom_ctor().
void Vatom_dtor (Vatom ** thee)
Object destructor.
Author:
Nathan Baker
Parameters:
thee Pointer to memory location of object to be destroyed
References Vatom_dtor2().
void Vatom_dtor2 (Vatom * thee)
FORTRAN stub object destructor.
Author:
Nathan Baker
Parameters:
thee Pointer to object to be destroyed
Referenced by Vatom_dtor().
double Vatom_getAtomID (Vatom * thee)
Get atom ID.
Author:
Nathan Baker
Parameters:
thee Vatom object
Returns:
Unique non-negative number
Referenced by Vacc_atomSASA(), Vacc_atomSASPoints(), Vacc_atomSurf(), Vacc_fastMolAcc(), Vacc_totalAtomdSASA(), and Vacc_totalAtomdSAV().
void Vatom_getAtomName (Vatom * thee, char atomName[VMAX_RECLEN])
Retrieve atom name.
Author:
Jason Wagoner
Parameters:
atomName Vatom object Atom name
References sVatom::atomName.
double Vatom_getCharge (Vatom * thee)
Get atomic charge.
Author:
Nathan Baker
Parameters:
thee Vatom object
Returns:
Atom partial charge (in e)
References sVatom::charge.
Referenced by fillcoChargeSpline1(), fillcoChargeSpline2(), fillcoPermanentMultipole(), initAPOL(), initMG(), qfForceSpline1(), qfForceSpline2(), qfForceSpline4(), Vfetk_PDE_delta(), Vgreen_coulomb_direct(), Vgreen_coulombD_direct(), Vpbe_ctor2(), Vpbe_getCoulombEnergy1(), Vpmg_polarizEnergy(), Vpmg_qfAtomEnergy(), and Vpmg_qfEnergyPoint().
double Vatom_getEpsilon (Vatom * thee)
Get atomic epsilon.
Author:
David Gohara
Parameters:
thee Vatom object
Returns:
Atomic epsilon (in Å)
double Vatom_getPartID (Vatom * thee)
Get partition ID.
Author:
Nathan Baker
Parameters:
thee Vatom object
Returns:
Partition ID; a negative value means this atom is not assigned to any partition
References sVatom::partID.
Referenced by Vfetk_getAtomColor().
double* Vatom_getPosition (Vatom * thee)
Get atomic position.
Author:
Nathan Baker
Parameters:
thee Vatom object
Returns:
Pointer to 3*double array of atomic coordinates (in Å)
References sVatom::position.
Referenced by fillcoChargeSpline1(), fillcoChargeSpline2(), fillcoCoefMolDielNoSmooth(), fillcoCoefMolIon(), fillcoCoefSpline(), fillcoCoefSpline3(), fillcoCoefSpline4(), fillcoPermanentMultipole(), forceAPOL(), initAPOL(), qfForceSpline1(), qfForceSpline2(), qfForceSpline4(), Vacc_atomSurf(), Vacc_SASA(), Vacc_splineAccAtom(), Vacc_splineAccGradAtomNorm(), Vacc_splineAccGradAtomNorm3(), Vacc_splineAccGradAtomNorm4(), Vacc_splineAccGradAtomUnnorm(), Vacc_totalAtomdSASA(), Vacc_totalAtomdSAV(), Vacc_wcaForceAtom(), Vcsm_init(), Vcsm_update(), Vfetk_PDE_delta(), Vgreen_coulomb_direct(), Vgreen_coulombD_direct(), Vpbe_ctor2(), Vpbe_getCoulombEnergy1(), Vpmg_dbForce(), Vpmg_ibForce(), Vpmg_polarizEnergy(), Vpmg_qfAtomEnergy(), and Vpmg_qfEnergyPoint().
double Vatom_getRadius (Vatom * thee)
Get atomic position.
Author:
Nathan Baker
Parameters:
thee Vatom object
Returns:
Atomic radius (in Å)
References sVatom::radius.
Referenced by fillcoCoefMolDielNoSmooth(), fillcoCoefMolIon(), fillcoCoefSpline(), fillcoCoefSpline3(), fillcoCoefSpline4(), initAPOL(), Vacc_atomSurf(), Vacc_splineAccAtom(), Vacc_splineAccGradAtomNorm(), Vacc_splineAccGradAtomNorm3(), Vacc_splineAccGradAtomNorm4(), Vacc_splineAccGradAtomUnnorm(), Vacc_storeParms(), Vacc_totalAtomdSASA(), Vacc_totalAtomdSAV(), Vpbe_ctor2(), Vpmg_dbForce(), and Vpmg_ibForce().
void Vatom_getResName (Vatom * thee, char resName[VMAX_RECLEN])
Retrieve residue name.
Author:
Jason Wagoner
Parameters:
thee Vatom object
resName Residue Name
References sVatom::resName.
unsigned long int Vatom_memChk (Vatom * thee)
Return the memory used by this structure (and its contents) in bytes.
Author:
Nathan Baker
Parameters:
thee Vpmg object
Returns:
The memory used by this structure and its contents in bytes
void Vatom_setAtomID (Vatom * thee, int id)
Set atom ID.
Author:
Nathan Baker
Parameters:
thee Vatom object
id Unique non-negative number
Referenced by Valist_readPDB(), Valist_readPQR(), and Valist_readXML().
void Vatom_setAtomName (Vatom * thee, char atomName[VMAX_RECLEN])
Set atom name.
Author:
Jason Wagoner
Parameters:
atomName Vatom object Atom name
References sVatom::atomName.
Referenced by Valist_readPDB(), and Valist_readPQR().
void Vatom_setCharge (Vatom * thee, double charge)
Set atomic charge.
Author:
Nathan Baker
Parameters:
thee Vatom object
charge Atom partial charge (in e)
References sVatom::charge.
Referenced by Valist_readPDB(), Valist_readPQR(), and Valist_readXML().
void Vatom_setEpsilon (Vatom * thee, double epsilon)
Set atomic epsilon.
Author:
David Gohara
Parameters:
thee Vatom object
epsilon Atomic epsilon (in Å)
Referenced by Valist_readPDB(), and Valist_readPQR().
void Vatom_setPartID (Vatom * thee, int partID)
Set partition ID.
Author:
Nathan Baker
Parameters:
thee Vatom object
partID Partition ID; a negative value means this atom is not assigned to any partition
References sVatom::partID.
Referenced by Vfetk_setAtomColors().
void Vatom_setPosition (Vatom * thee, double position[3])
Set the atomic position.
Author:
Nathan Baker
Parameters:
thee Vatom object to be modified
position Coordinates (in Å)
References sVatom::position.
Referenced by Valist_readPDB(), Valist_readPQR(), and Valist_readXML().
void Vatom_setRadius (Vatom * thee, double radius)
Set atomic radius.
Author:
Nathan Baker
Parameters:
thee Vatom object
radius Atomic radius (in Å)
References sVatom::radius.
Referenced by Valist_readPDB(), Valist_readPQR(), and Valist_readXML().
void Vatom_setResName (Vatom * thee, char resName[VMAX_RECLEN])
Set residue name.
Author:
Jason Wagoner
Parameters:
thee Vatom object
resName Residue Name
References sVatom::resName.
Referenced by Valist_readPDB(), and Valist_readPQR().