APBS: MGparm class
MGparm class
Parameter which holds useful parameters for generic multigrid calculations.
Data Structures
struct sMGparm
Parameter structure for MG-specific variables from input files.
Files
file mgparm.h
Contains declarations for class MGparm.
file mgparm.c
Class MGparm methods.
Typedefs
typedef enum eMGparm_CalcType MGparm_CalcType
Declare MGparm_CalcType type.
typedef enum eMGparm_CentMeth MGparm_CentMeth
Declare MGparm_CentMeth type.
typedef struct sMGparm MGparm
Declaration of the MGparm class as the MGparm structure.
Enumerations
enum eMGparm_CalcType {
MCT_MANUAL = 0,
MCT_AUTO = 1,
MCT_PARALLEL = 2,
MCT_DUMMY = 3,
MCT_NONE = 4
}
Calculation type.
enum eMGparm_CentMeth {
MCM_POINT = 0,
MCM_MOLECULE = 1,
MCM_FOCUS = 2
}
Centering method.
Functions
Vrc_Codes APOLparm_parseToken (APOLparm *thee, char tok[VMAX_BUFSIZE], Vio *sock)
Parse an MG keyword from an input file.
Vrc_Codes FEMparm_parseToken (FEMparm *thee, char tok[VMAX_BUFSIZE], Vio *sock)
Parse an MG keyword from an input file.
int MGparm_getNx (MGparm *thee)
Get number of grid points in x direction.
int MGparm_getNy (MGparm *thee)
Get number of grid points in y direction.
int MGparm_getNz (MGparm *thee)
Get number of grid points in z direction.
double MGparm_getHx (MGparm *thee)
Get grid spacing in x direction (Å).
double MGparm_getHy (MGparm *thee)
Get grid spacing in y direction (Å).
double MGparm_getHz (MGparm *thee)
Get grid spacing in z direction (Å).
void MGparm_setCenterX (MGparm *thee, double x)
Set center x-coordinate.
void MGparm_setCenterY (MGparm *thee, double y)
Set center y-coordinate.
void MGparm_setCenterZ (MGparm *thee, double z)
Set center z-coordinate.
double MGparm_getCenterX (MGparm *thee)
Get center x-coordinate.
double MGparm_getCenterY (MGparm *thee)
Get center y-coordinate.
double MGparm_getCenterZ (MGparm *thee)
Get center z-coordinate.
MGparm * MGparm_ctor (MGparm_CalcType type)
Construct MGparm object.
Vrc_Codes MGparm_ctor2 (MGparm *thee, MGparm_CalcType type)
FORTRAN stub to construct MGparm object.
void MGparm_dtor (MGparm **thee)
Object destructor.
void MGparm_dtor2 (MGparm *thee)
FORTRAN stub for object destructor.
Vrc_Codes MGparm_check (MGparm *thee)
Consistency check for parameter values stored in object.
void MGparm_copy (MGparm *thee, MGparm *parm)
Copy MGparm object into thee.
Vrc_Codes MGparm_parseToken (MGparm *thee, char tok[VMAX_BUFSIZE], Vio *sock)
Parse an MG keyword from an input file.
Detailed Description
Parameter which holds useful parameters for generic multigrid calculations.
Enumeration Type Documentation
enum eMGparm_CalcType
Calculation type.
Enumerator:
MCT_MANUAL
mg-manual
MCT_AUTO
mg-auto
MCT_PARALLEL
mg-para
MCT_DUMMY
mg-dummy
MCT_NONE
unspecified
enum eMGparm_CentMeth
Centering method.
Enumerator:
MCM_POINT
Center on a point
MCM_MOLECULE
Center on a molecule
MCM_FOCUS
Determined by focusing
Function Documentation
Vrc_Codes APOLparm_parseToken (APOLparm * thee, char tok[VMAX_BUFSIZE], Vio * sock)
Parse an MG keyword from an input file.
Author:
David Gohara
Parameters:
thee MGparm object
tok Token to parse
sock Stream for more tokens
Returns:
Success enumeration (1 if matched and assigned; -1 if matched, but there's some sort of error (i.e., too few args); 0 if not matched)
References VRC_FAILURE, and Vstring_strcasecmp().
Vrc_Codes FEMparm_parseToken (FEMparm * thee, char tok[VMAX_BUFSIZE], Vio * sock)
Parse an MG keyword from an input file.
Author:
Nathan Baker
Parameters:
thee MGparm object
tok Token to parse
sock Stream for more tokens
Returns:
VRC_SUCCESS if matched and assigned; VRC_FAILURE if matched, but there's some sort of error (i.e., too few args); VRC_WARNING if not matched
References VRC_FAILURE, and Vstring_strcasecmp().
Vrc_Codes MGparm_check (MGparm * thee)
Consistency check for parameter values stored in object.
Author:
Nathan Baker
Parameters:
thee MGparm object
Returns:
Success enumeration
References sMGparm::dime, MCT_AUTO, MCT_DUMMY, MCT_MANUAL, MCT_PARALLEL, sMGparm::nlev, sMGparm::parsed, sMGparm::setcgcent, sMGparm::setcglen, sMGparm::setchgm, sMGparm::setdime, sMGparm::setfgcent, sMGparm::setfglen, sMGparm::setgcent, sMGparm::setglen, sMGparm::setgrid, sMGparm::setofrac, sMGparm::setpdime, sMGparm::setrank, sMGparm::setsize, sMGparm::setUseAqua, sMGparm::type, sMGparm::useAqua, VMGNLEV, VRC_FAILURE, and VRC_SUCCESS.
void MGparm_copy (MGparm * thee, MGparm * parm)
Copy MGparm object into thee.
Author:
Nathan Baker and Todd Dolinsky
Parameters:
thee MGparm object (target for copy)
parm MGparm object (source for copy)
References sMGparm::async, sMGparm::ccenter, sMGparm::ccentmol, sMGparm::ccmeth, sMGparm::center, sMGparm::centmol, sMGparm::cglen, sMGparm::chgm, sMGparm::chgs, sMGparm::cmeth, sMGparm::dime, sMGparm::fcenter, sMGparm::fcentmol, sMGparm::fcmeth, sMGparm::fglen, sMGparm::glen, sMGparm::grid, sMGparm::method, sMGparm::nlev, sMGparm::nonlintype, sMGparm::ofrac, sMGparm::parsed, sMGparm::partDisjCenter, sMGparm::partDisjLength, sMGparm::partDisjOwnSide, sMGparm::pdime, sMGparm::proc_rank, sMGparm::proc_size, sMGparm::setasync, sMGparm::setcgcent, sMGparm::setcglen, sMGparm::setchgm, sMGparm::setdime, sMGparm::setfgcent, sMGparm::setfglen, sMGparm::setgcent, sMGparm::setglen, sMGparm::setgrid, sMGparm::setnlev, sMGparm::setnonlintype, sMGparm::setofrac, sMGparm::setpdime, sMGparm::setrank, sMGparm::setsize, sMGparm::setUseAqua, sMGparm::type, and sMGparm::useAqua.
Referenced by NOsh_calc_copy().
MGparm* MGparm_ctor (MGparm_CalcType type)
Construct MGparm object.
Author:
Nathan Baker
Parameters:
type Type of MG calculation
Returns:
Newly allocated and initialized MGparm object
References MGparm_ctor2(), and VRC_SUCCESS.
Referenced by NOsh_calc_ctor().
Vrc_Codes MGparm_ctor2 (MGparm * thee, MGparm_CalcType type)
FORTRAN stub to construct MGparm object.
Author:
Nathan Baker and Todd Dolinsky
Parameters:
thee Space for MGparm object
type Type of MG calculation
Returns:
Success enumeration
References sMGparm::chgs, sMGparm::dime, sMGparm::nlev, sMGparm::parsed, sMGparm::partDisjOwnSide, sMGparm::pdime, sMGparm::setasync, sMGparm::setcgcent, sMGparm::setcglen, sMGparm::setchgm, sMGparm::setdime, sMGparm::setfgcent, sMGparm::setfglen, sMGparm::setgcent, sMGparm::setglen, sMGparm::setgrid, sMGparm::setnlev, sMGparm::setofrac, sMGparm::setpdime, sMGparm::setrank, sMGparm::setsize, sMGparm::setUseAqua, sMGparm::type, sMGparm::useAqua, VCM_CHARGE, VMGNLEV, VRC_FAILURE, and VRC_SUCCESS.
Referenced by MGparm_ctor().
void MGparm_dtor (MGparm ** thee)
Object destructor.
Author:
Nathan Baker
Parameters:
thee Pointer to memory location of MGparm object
References MGparm_dtor2().
Referenced by NOsh_calc_dtor().
void MGparm_dtor2 (MGparm * thee)
FORTRAN stub for object destructor.
Author:
Nathan Baker
Parameters:
thee Pointer to MGparm object
Referenced by MGparm_dtor().
double MGparm_getCenterX (MGparm * thee)
Get center x-coordinate.
Author:
Nathan Baker
Parameters:
thee MGparm object
Returns:
x-coordinate
References sMGparm::center.
double MGparm_getCenterY (MGparm * thee)
Get center y-coordinate.
Author:
Nathan Baker
Parameters:
thee MGparm object
Returns:
y-coordinate
References sMGparm::center.
double MGparm_getCenterZ (MGparm * thee)
Get center z-coordinate.
Author:
Nathan Baker
Parameters:
thee MGparm object
Returns:
z-coordinate
References sMGparm::center.
double MGparm_getHx (MGparm * thee)
Get grid spacing in x direction (Å).
Author:
Nathan Baker
Parameters:
thee MGparm object
Returns:
Grid spacing in the x direction
References sMGparm::grid.
double MGparm_getHy (MGparm * thee)
Get grid spacing in y direction (Å).
Author:
Nathan Baker
Parameters:
thee MGparm object
Returns:
Grid spacing in the y direction
References sMGparm::grid.
double MGparm_getHz (MGparm * thee)
Get grid spacing in z direction (Å).
Author:
Nathan Baker
Parameters:
thee MGparm object
Returns:
Grid spacing in the z direction
References sMGparm::grid.
int MGparm_getNx (MGparm * thee)
Get number of grid points in x direction.
Author:
Nathan Baker
Parameters:
thee MGparm object
Returns:
Number of grid points in the x direction
References sMGparm::dime.
int MGparm_getNy (MGparm * thee)
Get number of grid points in y direction.
Author:
Nathan Baker
Parameters:
thee MGparm object
Returns:
Number of grid points in the y direction
References sMGparm::dime.
int MGparm_getNz (MGparm * thee)
Get number of grid points in z direction.
Author:
Nathan Baker
Parameters:
thee MGparm object
Returns:
Number of grid points in the z direction
References sMGparm::dime.
Vrc_Codes MGparm_parseToken (MGparm * thee, char tok[VMAX_BUFSIZE], Vio * sock)
Parse an MG keyword from an input file.
Author:
Nathan Baker and Todd Dolinsky
Parameters:
thee MGparm object
tok Token to parse
sock Stream for more tokens
Returns:
Success enumeration (1 if matched and assigned; -1 if matched, but there's some sort of error (i.e., too few args); 0 if not matched)
References VRC_FAILURE, and Vstring_strcasecmp().
void MGparm_setCenterX (MGparm * thee, double x)
Set center x-coordinate.
Author:
Nathan Baker
Parameters:
thee MGparm object
x x-coordinate
References sMGparm::center.
void MGparm_setCenterY (MGparm * thee, double y)
Set center y-coordinate.
Author:
Nathan Baker
Parameters:
thee MGparm object
y y-coordinate
References sMGparm::center.
void MGparm_setCenterZ (MGparm * thee, double z)
Set center z-coordinate.
Author:
Nathan Baker
Parameters:
thee MGparm object
z z-coordinate
References sMGparm::center.