APBS: PBEparm class
PBEparm class
Parameter structure for PBE variables independent of solver.
Data Structures
struct sPBEparm
Parameter structure for PBE variables from input files.
Files
file pbeparm.h
Contains declarations for class PBEparm.
file pbeparm.c
Class PBEparm methods.
Defines
#define PBEPARM_MAXWRITE 10
Number of things that can be written out in a single calculation.
Typedefs
typedef enum ePBEparm_calcEnergy PBEparm_calcEnergy
Define ePBEparm_calcEnergy enumeration as PBEparm_calcEnergy.
typedef enum ePBEparm_calcForce PBEparm_calcForce
Define ePBEparm_calcForce enumeration as PBEparm_calcForce.
typedef struct sPBEparm PBEparm
Declaration of the PBEparm class as the PBEparm structure.
Enumerations
enum ePBEparm_calcEnergy {
PCE_NO = 0,
PCE_TOTAL = 1,
PCE_COMPS = 2
}
Define energy calculation enumeration.
enum ePBEparm_calcForce {
PCF_NO = 0,
PCF_TOTAL = 1,
PCF_COMPS = 2
}
Define force calculation enumeration.
Functions
double PBEparm_getIonCharge (PBEparm *thee, int iion)
Get charge (e) of specified ion species.
double PBEparm_getIonConc (PBEparm *thee, int iion)
Get concentration (M) of specified ion species.
double PBEparm_getIonRadius (PBEparm *thee, int iion)
Get radius (A) of specified ion species.
PBEparm * PBEparm_ctor ()
Construct PBEparm object.
int PBEparm_ctor2 (PBEparm *thee)
FORTRAN stub to construct PBEparm object.
void PBEparm_dtor (PBEparm **thee)
Object destructor.
void PBEparm_dtor2 (PBEparm *thee)
FORTRAN stub for object destructor.
int PBEparm_check (PBEparm *thee)
Consistency check for parameter values stored in object.
void PBEparm_copy (PBEparm *thee, PBEparm *parm)
Copy PBEparm object into thee.
int PBEparm_parseToken (PBEparm *thee, char tok[VMAX_BUFSIZE], Vio *sock)
Parse a keyword from an input file.
Detailed Description
Parameter structure for PBE variables independent of solver.
Enumeration Type Documentation
enum ePBEparm_calcEnergy
Define energy calculation enumeration.
Enumerator:
PCE_NO Do not perform energy calculation
PCE_TOTAL Calculate total energy only
PCE_COMPS Calculate per-atom energy components
enum ePBEparm_calcForce
Define force calculation enumeration.
Enumerator:
PCF_NO Do not perform force calculation
PCF_TOTAL Calculate total force only
PCF_COMPS Calculate per-atom force components
Function Documentation
int PBEparm_check (PBEparm * thee)
Consistency check for parameter values stored in object.
Author:
Nathan Baker
Returns:
1 if OK, 0 otherwise
Parameters:
thee Object to be checked
References sPBEparm::calcenergy, sPBEparm::calcforce, sPBEparm::nion, sPBEparm::parsed, PCE_NO, PCF_NO, sPBEparm::setbcfl, sPBEparm::setcalcenergy, sPBEparm::setcalcforce, sPBEparm::setion, sPBEparm::setmolid, sPBEparm::setnion, sPBEparm::setpbetype, sPBEparm::setpdie, sPBEparm::setsdens, sPBEparm::setsdie, sPBEparm::setsrad, sPBEparm::setsrfm, sPBEparm::setswin, sPBEparm::settemp, sPBEparm::setwritemat, sPBEparm::srad, sPBEparm::srfm, VSM_MOL, VSM_MOLSMOOTH, VSM_SPLINE, VSM_SPLINE3, VSM_SPLINE4, and sPBEparm::writemat.
void PBEparm_copy (PBEparm * thee, PBEparm * parm)
Copy PBEparm object into thee.
Author:
Nathan Baker
Parameters:
parm Target for copy Source for copy
References sPBEparm::bcfl, sPBEparm::calcenergy, sPBEparm::calcforce, sPBEparm::chargeMapID, sPBEparm::dielMapID, sPBEparm::ionc, sPBEparm::ionq, sPBEparm::ionr, sPBEparm::kappaMapID, MAXION, sPBEparm::molid, sPBEparm::nion, sPBEparm::numwrite, sPBEparm::parsed, PBEPARM_MAXWRITE, sPBEparm::pbetype, sPBEparm::pdie, sPBEparm::sdens, sPBEparm::sdie, sPBEparm::setbcfl, sPBEparm::setcalcenergy, sPBEparm::setcalcforce, sPBEparm::setion, sPBEparm::setmolid, sPBEparm::setnion, sPBEparm::setpbetype, sPBEparm::setpdie, sPBEparm::setsdens, sPBEparm::setsdie, sPBEparm::setsmsize, sPBEparm::setsmvolume, sPBEparm::setsrad, sPBEparm::setsrfm, sPBEparm::setswin, sPBEparm::settemp, sPBEparm::setwritemat, sPBEparm::smsize, sPBEparm::smvolume, sPBEparm::srad, sPBEparm::srfm, sPBEparm::swin, sPBEparm::temp, sPBEparm::useChargeMap, sPBEparm::useDielMap, sPBEparm::useKappaMap, sPBEparm::writefmt, sPBEparm::writemat, sPBEparm::writematflag, sPBEparm::writematstem, sPBEparm::writestem, and sPBEparm::writetype.
Referenced by NOsh_calc_copy().
PBEparm* PBEparm_ctor ()
Construct PBEparm object.
Author:
Nathan Baker
Returns:
Newly allocated and initialized PBEparm object
References PBEparm_ctor2().
Referenced by NOsh_calc_ctor().
int PBEparm_ctor2 (PBEparm * thee)
FORTRAN stub to construct PBEparm object.
Author:
Nathan Baker
Returns:
1 if succesful, 0 otherwise
Parameters:
thee Memory location for object
References sPBEparm::ionc, sPBEparm::ionq, sPBEparm::ionr, MAXION, sPBEparm::nion, sPBEparm::numwrite, sPBEparm::parsed, sPBEparm::sdens, sPBEparm::setbcfl, sPBEparm::setcalcenergy, sPBEparm::setcalcforce, sPBEparm::setion, sPBEparm::setmolid, sPBEparm::setnion, sPBEparm::setpbetype, sPBEparm::setpdie, sPBEparm::setsdens, sPBEparm::setsdie, sPBEparm::setsmsize, sPBEparm::setsmvolume, sPBEparm::setsrad, sPBEparm::setsrfm, sPBEparm::setswin, sPBEparm::settemp, sPBEparm::setwritemat, sPBEparm::smsize, sPBEparm::smvolume, sPBEparm::srad, sPBEparm::swin, sPBEparm::useChargeMap, sPBEparm::useDielMap, and sPBEparm::useKappaMap.
Referenced by PBEparm_ctor().
void PBEparm_dtor (PBEparm ** thee)
Object destructor.
Author:
Nathan Baker
Parameters:
thee Pointer to memory location of object
References PBEparm_dtor2().
Referenced by NOsh_calc_dtor().
void PBEparm_dtor2 (PBEparm * thee)
FORTRAN stub for object destructor.
Author:
Nathan Baker
Parameters:
thee Pointer to object to be destroyed
Referenced by PBEparm_dtor().
double PBEparm_getIonCharge (PBEparm * thee, int iion)
Get charge (e) of specified ion species.
Author:
Nathan Baker
Returns:
Charge of ion species (e)
Parameters:
iion PBEparm object Ion species ID/index
References sPBEparm::ionq.
double PBEparm_getIonConc (PBEparm * thee, int iion)
Get concentration (M) of specified ion species.
Author:
Nathan Baker
Returns:
Concentration of ion species (M)
Parameters:
iion PBEparm object Ion species ID/index
References sPBEparm::ionc.
double PBEparm_getIonRadius (PBEparm * thee, int iion)
Get radius (A) of specified ion species.
Author:
Nathan Baker
Returns:
Radius of ion species (A)
Parameters:
iion PBEparm object Ion species ID/index
References sPBEparm::ionr.
int PBEparm_parseToken (PBEparm * thee, char tok[VMAX_BUFSIZE], Vio * sock)
Parse a keyword from an input file.
Author:
Nathan Baker
Returns:
1 if matched and assigned; -1 if matched, but there's some sort of error (i.e., too few args); 0 if not matched
Parameters:
tok Parsing object
sock Token to parse Socket for additional tokens
References Vstring_strcasecmp().