APBS: Vparam class
Vparam class
Reads and assigns charge/radii parameters.
Data Structures
struct sVparam_AtomData
AtomData sub-class; stores atom data.
struct Vparam_ResData
ResData sub-class; stores residue data.
struct Vparam
Reads and assigns charge/radii parameters.
Files
file vparam.h
Contains declarations for class Vparam.
file vparam.c
Class Vparam methods.
Typedefs
typedef struct sVparam_AtomData Vparam_AtomData
Declaration of the Vparam_AtomData class as the sVparam_AtomData structure.
typedef struct Vparam_ResData Vparam_ResData
Declaration of the Vparam_ResData class as the Vparam_ResData structure.
typedef struct Vparam Vparam
Declaration of the Vparam class as the Vparam structure.
Functions
unsigned long int Vparam_memChk (Vparam *thee)
Get number of bytes in this object and its members.
Vparam_AtomData * Vparam_AtomData_ctor ()
Construct the object.
int Vparam_AtomData_ctor2 (Vparam_AtomData *thee)
FORTRAN stub to construct the object.
void Vparam_AtomData_dtor (Vparam_AtomData **thee)
Destroy object.
void Vparam_AtomData_dtor2 (Vparam_AtomData *thee)
FORTRAN stub to destroy object.
void Vparam_AtomData_copyTo (Vparam_AtomData *thee, Vparam_AtomData *dest)
Copy current atom object to destination.
void Vparam_ResData_copyTo (Vparam_ResData *thee, Vparam_ResData *dest)
Copy current residue object to destination.
void Vparam_AtomData_copyFrom (Vparam_AtomData *thee, Vparam_AtomData *src)
Copy current atom object from another.
Vparam_ResData * Vparam_ResData_ctor (Vmem *mem)
Construct the object.
int Vparam_ResData_ctor2 (Vparam_ResData *thee, Vmem *mem)
FORTRAN stub to construct the object.
void Vparam_ResData_dtor (Vparam_ResData **thee)
Destroy object.
void Vparam_ResData_dtor2 (Vparam_ResData *thee)
FORTRAN stub to destroy object.
Vparam * Vparam_ctor ()
Construct the object.
int Vparam_ctor2 (Vparam *thee)
FORTRAN stub to construct the object.
void Vparam_dtor (Vparam **thee)
Destroy object.
void Vparam_dtor2 (Vparam *thee)
FORTRAN stub to destroy object.
Vparam_ResData * Vparam_getResData (Vparam *thee, char resName[VMAX_ARGLEN])
Get residue data.
Vparam_AtomData * Vparam_getAtomData (Vparam *thee, char resName[VMAX_ARGLEN], char atomName[VMAX_ARGLEN])
Get atom data.
int Vparam_readFlatFile (Vparam *thee, const char *iodev, const char *iofmt, const char *thost, const char *fname)
Read a flat-file format parameter database.
int Vparam_readXMLFile (Vparam *thee, const char *iodev, const char *iofmt, const char *thost, const char *fname)
Read an XML format parameter database.
VPRIVATE int readFlatFileLine (Vio *sock, Vparam_AtomData *atom)
Read a single line of the flat file database.
VPRIVATE int readXMLFileAtom (Vio *sock, Vparam_AtomData *atom)
Read atom information from an XML file.
Variables
VPRIVATE char * MCwhiteChars = " =,;\t\n\r"
Whitespace characters for socket reads.
VPRIVATE char * MCcommChars = "#%"
Comment characters for socket reads.
VPRIVATE char * MCxmlwhiteChars = " =,;\t\n\r<>"
Whitespace characters for XML socket reads.
Detailed Description
Reads and assigns charge/radii parameters.
Function Documentation
VPRIVATE int readFlatFileLine (Vio * sock, Vparam_AtomData * atom)
Read a single line of the flat file database.
Author:
Nathan Baker
Parameters:
sock Socket ready for reading
atom Atom to hold parsed data
Returns:
1 if successful, 0 otherwise
References sVparam_AtomData::atomName, sVparam_AtomData::charge, sVparam_AtomData::epsilon, sVparam_AtomData::radius, and sVparam_AtomData::resName.
Referenced by Vparam_readFlatFile().
VPRIVATE int readXMLFileAtom (Vio * sock, Vparam_AtomData * atom)
Read atom information from an XML file.
Author:
Todd Dolinsky
Parameters:
sock Socket ready for reading
atom Atom to hold parsed data
Returns:
1 if successful, 0 otherwise
References sVparam_AtomData::atomName, sVparam_AtomData::charge, sVparam_AtomData::epsilon, sVparam_AtomData::radius, and Vstring_strcasecmp().
Referenced by Vparam_readXMLFile().
void Vparam_AtomData_copyFrom (Vparam_AtomData * thee, Vparam_AtomData * src)
Copy current atom object from another.
Author:
Nathan Baker
Parameters:
thee Pointer to destination object
src Pointer to source object
References Vparam_AtomData_copyTo().
void Vparam_AtomData_copyTo (Vparam_AtomData * thee, Vparam_AtomData * dest)
Copy current atom object to destination.
Author:
Nathan Baker
Parameters:
thee Pointer to source object
dest Pointer to destination object
References sVparam_AtomData::atomName, sVparam_AtomData::charge, sVparam_AtomData::epsilon, sVparam_AtomData::radius, and sVparam_AtomData::resName.
Referenced by Vparam_AtomData_copyFrom(), Vparam_readFlatFile(), Vparam_readXMLFile(), and Vparam_ResData_copyTo().
Vparam_AtomData* Vparam_AtomData_ctor ()
Construct the object.
Author:
Nathan Baker
Returns:
Newly allocated object
References Vparam_AtomData_ctor2().
int Vparam_AtomData_ctor2 (Vparam_AtomData * thee)
FORTRAN stub to construct the object.
Author:
Nathan Baker
Parameters:
thee Allocated memory
Returns:
1 if successful, 0 otherwise
Referenced by Vparam_AtomData_ctor().
void Vparam_AtomData_dtor (Vparam_AtomData ** thee)
Destroy object.
Author:
Nathan Baker
Parameters:
thee Pointer to memory location of object
References Vparam_AtomData_dtor2().
void Vparam_AtomData_dtor2 (Vparam_AtomData * thee)
FORTRAN stub to destroy object.
Author:
Nathan Baker
Parameters:
thee Pointer to object
Referenced by Vparam_AtomData_dtor().
Vparam* Vparam_ctor ()
Construct the object.
Author:
Nathan Baker
Returns:
Newly allocated Vparam object
References Vparam_ctor2().
Referenced by loadParameter().
int Vparam_ctor2 (Vparam * thee)
FORTRAN stub to construct the object.
Author:
Nathan Baker
Parameters:
thee Allocated Vparam memory
Returns:
1 if successful, 0 otherwise
References nResData, resData, and vmem.
Referenced by Vparam_ctor().
void Vparam_dtor (Vparam ** thee)
Destroy object.
Author:
Nathan Baker
Parameters:
thee Pointer to memory location of object
References Vparam_dtor2().
Referenced by main().
void Vparam_dtor2 (Vparam * thee)
FORTRAN stub to destroy object.
Author:
Nathan Baker
Parameters:
thee Pointer to object
References nResData, resData, vmem, and Vparam_ResData_dtor2().
Referenced by Vparam_dtor().
Vparam_AtomData* Vparam_getAtomData (Vparam * thee, char resName[VMAX_ARGLEN], char atomName[VMAX_ARGLEN])
Get atom data.
Author:
Nathan Baker
Parameters:
thee Vparam object
resName Residue name
atomName Atom name
Returns:
Pointer to the desired atom object or VNULL if residue not found
Note:
Some method to initialize the database must be called before this method (e.g.,
See also:
Vparam_readFlatFile)
References Vparam_ResData::atomData, sVparam_AtomData::atomName, Vparam_ResData::nAtomData, nResData, resData, Vparam_getResData(), and Vstring_strcasecmp().
Referenced by initAPOL(), Valist_readPDB(), and Valist_readPQR().
Vparam_ResData* Vparam_getResData (Vparam * thee, char resName[VMAX_ARGLEN])
Get residue data.
Author:
Nathan Baker
Parameters:
thee Vparam object
resName Residue name
Returns:
Pointer to the desired residue object or VNULL if residue not found
Note:
Some method to initialize the database must be called before this method (e.g.,
See also:
Vparam_readFlatFile)
References Vparam_ResData::name, nResData, resData, and Vstring_strcasecmp().
Referenced by Vparam_getAtomData().
unsigned long int Vparam_memChk (Vparam * thee)
Get number of bytes in this object and its members.
Author:
Nathan Baker
Parameters:
thee Vparam object
Returns:
Number of bytes allocated for object
References vmem.
int Vparam_readFlatFile (Vparam * thee, const char * iodev, const char * iofmt, const char * thost, const char * fname)
Read a flat-file format parameter database.
Author:
Nathan Baker
Parameters:
thee Vparam object
iodev Input device type (FILE/BUFF/UNIX/INET)
iofmt Input device format (ASCII/XDR)
thost Input hostname (for sockets)
fname Input FILE/BUFF/UNIX/INET name (see note below for format)
Returns:
1 if successful, 0 otherwise
Note:
The database file should have the following format:
 RESIDUE ATOM CHARGE RADIUS EPSILON
where RESIDUE is the residue name string, ATOM is the atom name string, CHARGE is the charge in e, RADIUS is the van der Waals radius () in Å, and EPSILON is the van der Waals well-depth () in kJ/mol. See the Vparam structure documentation for the precise definitions of and .
ASCII-format flat files are provided with the APBS source code:
tools/conversion/vparam-amber-parm94.dat
AMBER parm94 parameters
tools/conversion/vparam-charmm-par_all27.dat
CHARMM par_all27_prot_na parameters
References Vparam_ResData::atomData, MCcommChars, Vparam_ResData::name, Vparam_ResData::nAtomData, nResData, readFlatFileLine(), resData, sVparam_AtomData::resName, vmem, Vparam_AtomData_copyTo(), Vparam_ResData_ctor2(), Vparam_ResData_dtor2(), and Vstring_strcasecmp().
Referenced by loadParameter().
int Vparam_readXMLFile (Vparam * thee, const char * iodev, const char * iofmt, const char * thost, const char * fname)
Read an XML format parameter database.
Author:
Todd Dolinsky
Parameters:
thee Vparam object
iodev Input device type (FILE/BUFF/UNIX/INET)
iofmt Input device format (ASCII/XDR)
thost Input hostname (for sockets)
fname Input FILE/BUFF/UNIX/INET name
Returns:
1 if successful, 0 otherwise
References Vparam_ResData::atomData, MCcommChars, Vparam_ResData::name, Vparam_ResData::nAtomData, nResData, readXMLFileAtom(), resData, vmem, Vparam_AtomData_copyTo(), Vparam_ResData_copyTo(), Vparam_ResData_ctor2(), Vparam_ResData_dtor2(), and Vstring_strcasecmp().
Referenced by loadParameter().
void Vparam_ResData_copyTo (Vparam_ResData * thee, Vparam_ResData * dest)
Copy current residue object to destination.
Author:
Todd Dolinsky
Parameters:
thee Pointer to source object
dest Pointer to destination object
References Vparam_ResData::atomData, Vparam_ResData::name, Vparam_ResData::nAtomData, Vparam_ResData::vmem, and Vparam_AtomData_copyTo().
Referenced by Vparam_readXMLFile().
Vparam_ResData* Vparam_ResData_ctor (Vmem * mem)
Construct the object.
Author:
Nathan Baker
Parameters:
mem Memory object of Vparam master class
Returns:
Newly allocated object
References Vparam_ResData_ctor2().
int Vparam_ResData_ctor2 (Vparam_ResData * thee, Vmem * mem)
FORTRAN stub to construct the object.
Author:
Nathan Baker
Parameters:
thee Allocated memory
mem Memory object of Vparam master class
Returns:
1 if successful, 0 otherwise
References Vparam_ResData::atomData, Vparam_ResData::nAtomData, and Vparam_ResData::vmem.
Referenced by Vparam_readFlatFile(), Vparam_readXMLFile(), and Vparam_ResData_ctor().
void Vparam_ResData_dtor (Vparam_ResData ** thee)
Destroy object.
Author:
Nathan Baker
Parameters:
thee Pointer to memory location of object
References Vparam_ResData_dtor2().
void Vparam_ResData_dtor2 (Vparam_ResData * thee)
FORTRAN stub to destroy object.
Author:
Nathan Baker
Parameters:
thee Pointer to object
References Vparam_ResData::atomData, Vparam_ResData::nAtomData, and Vparam_ResData::vmem.
Referenced by Vparam_dtor2(), Vparam_readFlatFile(), Vparam_readXMLFile(), and Vparam_ResData_dtor().