#
#
#
# $Id: $
#

# this is dummy target so this Makfile doesn't fail
all:

clean::
	cd apbs_radi && rm -f *.out mdin
	cd Solvation && rm -f *.out
	cd pbsa_pgb/iAPBS && rm -f *.out results
	cd Visualization && rm -f *.out *.dx
	cd smpbe && rm -f *.out *.dx
	cd apbs_solv && rm -f restrt mdout mdinfo
	cd Minimization && rm -f minim.out
	cd mm_pbsa && make clean


