##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Fri Mar 28 17:14:59 2014
##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path pot.pqr
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=0)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing swin...
PBEparm_parseToken:  trying swin...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing calcenergy...
PBEparm_parseToken:  trying calcenergy...
NOsh_parseMG:  Parsing calcforce...
PBEparm_parseToken:  trying calcforce...
NOsh_parseMG:  Parsing zmem...
PBEparm_parseToken:  trying zmem...
NOsh_parseMG:  Parsing lmem...
PBEparm_parseToken:  trying lmem...
NOsh_parseMG:  Parsing mdie...
PBEparm_parseToken:  trying mdie...
NOsh_parseMG:  Parsing memv...
PBEparm_parseToken:  trying memv...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (33, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Parsing PRINT section
NOsh: Done parsing PRINT section
NOsh: Done parsing PRINT section
NOsh: Done parsing file (got QUIT)
Valist_readPQR: Counted 1 atoms
Valist_getStatistics:  Max atom coordinate:  (0, 0, 4)
Valist_getStatistics:  Min atom coordinate:  (0, 0, 4)
Valist_getStatistics:  Molecule center:  (0, 0, 4)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 1.7637
Vpbe_ctor2:  solute dimensions = 3.5274 x 3.5274 x 3.5274
Vpbe_ctor2:  solute charge = 1
Vpbe_ctor2:  bulk ionic strength = 0.1
Vpbe_ctor2:  xkappa = 0.102972
Vpbe_ctor2:  Debye length = 9.71135
Vpbe_ctor2:  zkappa2 = 0.848263
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 7 x 7 x 7 table
Vclist_ctor2:  Using 7 x 7 x 7 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2.5 max radius
Vclist_setupGrid:  Grid lengths = (12.1089, 12.1089, 12.1089)
Vclist_setupGrid:  Grid lower corner = (-6.05445, -6.05445, -2.05445)
Vclist_assignAtoms:  Have 343 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 228.446
Vacc_storeParms:  Using 2246-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.000140
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Fri Mar 28 17:30:41 2014
##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path pot.pqr
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=0)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing swin...
PBEparm_parseToken:  trying swin...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing calcenergy...
PBEparm_parseToken:  trying calcenergy...
NOsh_parseMG:  Parsing calcforce...
PBEparm_parseToken:  trying calcforce...
NOsh_parseMG:  Parsing zmem...
PBEparm_parseToken:  trying zmem...
NOsh_parseMG:  Parsing lmem...
PBEparm_parseToken:  trying lmem...
NOsh_parseMG:  Parsing mdie...
PBEparm_parseToken:  trying mdie...
NOsh_parseMG:  Parsing memv...
PBEparm_parseToken:  trying memv...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (33, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Parsing PRINT section
NOsh: Done parsing PRINT section
NOsh: Done parsing PRINT section
NOsh: Done parsing file (got QUIT)
Valist_readPQR: Counted 1 atoms
Valist_getStatistics:  Max atom coordinate:  (0, 0, 4)
Valist_getStatistics:  Min atom coordinate:  (0, 0, 4)
Valist_getStatistics:  Molecule center:  (0, 0, 4)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 1.7637
Vpbe_ctor2:  solute dimensions = 3.5274 x 3.5274 x 3.5274
Vpbe_ctor2:  solute charge = 1
Vpbe_ctor2:  bulk ionic strength = 0.1
Vpbe_ctor2:  xkappa = 0.102972
Vpbe_ctor2:  Debye length = 9.71135
Vpbe_ctor2:  zkappa2 = 0.848263
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 7 x 7 x 7 table
Vclist_ctor2:  Using 7 x 7 x 7 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2.5 max radius
Vclist_setupGrid:  Grid lengths = (12.1089, 12.1089, 12.1089)
Vclist_setupGrid:  Grid lower corner = (-6.05445, -6.05445, -2.05445)
Vclist_assignAtoms:  Have 343 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 228.446
Vacc_storeParms:  Using 2246-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.000154
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Here is the value of kappa: 0.102972
Here is the value of L: 20.000000
Here is the value of zmem: -10.000000
Here is the value of mdie: 2.000000
Here is the value of memv: -2.000000
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 4.830000e-03
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (033, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 2.559000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vbuildops: Galer: (005, 005, 005)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 3.833000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 2.413900e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 5.445132e-02
Vprtstp: contraction number = 5.445132e-02
Vprtstp: iteration = 2
Vprtstp: relative residual = 3.555417e-03
Vprtstp: contraction number = 6.529534e-02
Vprtstp: iteration = 3
Vprtstp: relative residual = 2.369850e-04
Vprtstp: contraction number = 6.665461e-02
Vprtstp: iteration = 4
Vprtstp: relative residual = 1.588333e-05
Vprtstp: contraction number = 6.702252e-02
Vprtstp: iteration = 5
Vprtstp: relative residual = 1.068990e-06
Vprtstp: contraction number = 6.730262e-02
Vprtstp: iteration = 6
Vprtstp: relative residual = 7.231292e-08
Vprtstp: contraction number = 6.764605e-02
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 1.506300e-02
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 2.303400e-02
Vpmg_setPart:  lower corner = (-150, -150, -150)
Vpmg_setPart:  upper corner = (150, 150, 150)
Vpmg_setPart:  actual minima = (-150, -150, -150)
Vpmg_setPart:  actual maxima = (150, 150, 150)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vpmg_energy:  calculating only q-phi energy
Vpmg_qfEnergyVolume:  Calculating energy
Vpmg_energy:  qfEnergy = 4.595272002837E-01 kT
Vpmg_qfEnergyVolume:  Calculating energy
Vpmg_qmEnergy:  Calculating linear energy
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 8.260000e-04
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 4.000000e-06
printEnergy:  Performing global reduction (sum)
Vcom_reduce:  Not compiled with MPI, doing simple copy.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 3.527700e-02
