#!/bin/bash

if [[ $1 = "" ]]; then
    echo "Please use \"make test\" to run the tests."
    exit
fi


logfile=TESTRESULTS.log
nettime=0

input=( apbs-mol apbs-smol apbs-spl2 ) 

acetic=( -2.267873880748E+01 -2.233042654941E+01 -3.579918772262E+01 ) 
acetate=( -1.997461573276E+02 -1.984881352623E+02 -2.317244846973E+02 ) 
proton=( -2.974598683157E+02 -2.959669997009E+02 -3.670680616644E+02 )
ionization=( -4.745272868358E+02 -4.721247084138E+02 -5.629933586391E+02 )

# Initialize the results file

echo "# This file is automatically generated by test.sh." >> $logfile
echo "# INPUT NAME |  TEST RESULT | ACETIC | ACETATE | PROTON | IONIZATION | TIME" >> $logfile

# For each file in the directory, run APBS and get the value

for i in 0 1 2 
do
  echo "----------------------------------------"
  echo "Testing input file ${input[i]}.in"
  echo ""

 
  starttime=`date +%s`
  $1 ${input[i]}.in > ${input[i]}.out 
  answer=( `grep "Global net" ${input[i]}.out | awk '{print $5}'` )

  pass=PASSED
  sync

  echo "Acetic Acid Energy: ${answer[0]}"
  if [[ ${answer[0]} != ${acetic[i]} ]]; then
      echo "   Expected result is ${acetic[i]}"
      pass=FAILED
  fi

  echo "Acetate Energy    : ${answer[1]}"
  if [[ ${answer[1]} != ${acetate[i]} ]]; then
      echo "   Expected result is ${acetate[i]}"
      pass=FAILED
  fi

  echo "Proton Energy     : ${answer[2]}"
  if [[ ${answer[2]} != ${proton[i]} ]]; then
      echo "   Expected result is ${proton[i]}"
      pass=FAILED
  fi

  echo "Ionization Energy : ${answer[3]}"
  if [[ ${answer[3]} != ${ionization[i]} ]]; then
      echo "   Expected result is ${ionization[i]}"
      pass=FAILED
  fi

  
  if [[ $pass = "FAILED" ]]; then
      echo "*** FAILED ***"
  else
      pass=PASSED
      echo "*** PASSED ***"
  fi

 

  endtime=`date +%s`
  let elapsed=$endtime-$starttime
  let nettime=$nettime+$elapsed
  echo "Total elapsed time: $elapsed seconds"
  echo "----------------------------------------"

  # Put the results of all the tests in TEST-RESULTS.log

  echo "${input[i]} $pass ${answer[0]} ${answer[1]} ${answer[2]} ${answer[3]}  $elapsed" >> $logfile

done

echo "Test results have been logged to ${logfile}."
echo "Total time for this directory: ${nettime} seconds."
