#! /bin/sh
### ##########################################################################
### MALOC = < Minimal Abstraction Layer for Object-oriented C >
### Copyright (C) 1994--2000  Michael Holst
###
### This program is free software; you can redistribute it and/or modify it
### under the terms of the GNU General Public License as published by the
### Free Software Foundation; either version 2 of the License, or (at your
### option) any later version.
###
### This program is distributed in the hope that it will be useful,
### but WITHOUT ANY WARRANTY; without even the implied warranty of
### MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
### See the GNU General Public License for more details.
###
### You should have received a copy of the GNU General Public License along
### with this program; if not, write to the Free Software Foundation, Inc.,
### 675 Mass Ave, Cambridge, MA 02139, USA.
###
### Linking APBS statically or dynamically with other modules is making a
### combined work based on APBS. Thus, the terms and conditions of the GNU
### General Public License cover the whole combination.
### 
### SPECIAL GPL EXCEPTION
### In addition, as a special exception, the copyright holders of APBS
### give you permission to combine the APBS program with free software
### programs or libraries that are released under the GNU LGPL and with
### code included in releases of ISIM, PMV, PyMOL, SMOL, VMD.  This
### special exception permission is also extended to any software listed
### in the SPECIAL GPL EXCEPTION clauses by the PMG, FEtk, MC, or MALOC
### libraries.
### 
### Note that people who make modified versions of APBS are not obligated
### to grant this special exception for their modified versions; it is
### their choice whether to do so. The GNU General Public License gives
### permission to release a modified version without this exception; this
### exception also makes it possible to release a modified version which
### carries forward this exception.
###
### rcsid="$Id$"
### ##########################################################################

##############################################################################
# File:    bootstrap
#
# Purpose: Auto-generate the GNU configure script.
#          (WITH LIBTOOL AND AUTOHEADER.)
#
# Author:  Michael Holst
##############################################################################

rm -rf config.cache autom4te.cache

aclocal \
&& automake --gnu --add-missing --copy \
&& autoconf \
&& autoheader \
&& libtoolize --automake --copy --force

rm -rf config.cache autom4te.cache

