#! /bin/sh

##############################################################################
# File:    bootstrapapp
#
# Purpose: Auto-generate the GNU configure script.
#          (WITHOUT LIBTOOL OR AUTOHEADER.)
#
# Author:  Michael Holst
##############################################################################

rm -f config.cache

aclocal \
&& automake --gnu --add-missing --copy \
&& autoconf

