#! /bin/sh

##############################################################################
# File:    bootstrap
#
# Purpose: Auto-generate the GNU configure script.
#          (WITH LIBTOOL AND AUTOHEADER.)
#
# Author:  Michael Holst
##############################################################################

rm -f config.cache

aclocal \
&& automake --gnu --add-missing --copy \
&& autoconf \
&& autoheader \
&& libtoolize --automake --copy --force

