Import('env')

if GetOption('swig'):
    Default(env.LoadableModule('_pMC_mult', ['pMC_mult.cpp', 'pMC_mult.i']))
else:
    Default(env.LoadableModule('_pMC_mult', ['pMC_mult.cpp', 'pMC_mult_wrap.cpp']))

SConscript('substruct/SConscript')