#!/bin/bash

bindir='../../../bin/'

radii='1.00 2.00 3.00 4.00 5.00 6.00'

for i in $radii; do
  echo "Generating ion with $i radius..."
  echo "ATOM      1  I   ION     1       0.000   0.000  0.000  1.00  $i" \
    > ion.pqr
  ${bindir}/apbs apbs.in > OUTPUT-${i} 2>&1 
done
