name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        #os: [ ubuntu-latest, macos-latest ]
        #os: [ ubuntu-latest, macos-latest, windows-latest ]
        #python-version: [ 3.6, 3.7 ]
        python-version: [ 3.6 ]
        test-name : [ born,
                      actin-dimer-auto
                    ]
#actin-dimer-parallel
#alkanes
#born
#FKBP
#geoflow
#hca-bind
#ion-pmf
#ion-protein
#ionize
#pka-lig
#point-pmf
#solv
#protein-rn
#]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Prereqs
        uses: mstksg/get-package@v1
        with:
          apt-get: bison flex swig
      - name: Final Build 
        run: |
          echo "WHERE AM I"
          pwd 

          echo "VERSIONS:"
          echo "PYTHON VERSION"
          python -c "import sys; print(sys.version)"
          echo "CMAKE VERSION"
          cmake --version
          echo "Gcc VERSION"
          gcc --version
          echo "G++ VERSION"
          g++ --version
          echo "SWIG VERSION"
          swig -version

          pip3 install -U pip
          pip3 install -U pytest 
          pip3 install -U virtualenv
          pip3 install -U numpy

          #  Just build APBS for now
          echo "PWD FOR TOP DIR"
          pwd

          cd apbs
          echo "PWD FOR APBS SRC"
          pwd

          mkdir build
          cd build

          echo "BUILD DIR"
          pwd

          echo "RUN CMAKE"
          pwd
          echo "cmake -DENABLE_PYTHON=ON -DENABLE_GEOFLOW=ON -DBUILD_DOC=OFF -DBUILD_SHARED_LIBS=ON -DENABLE_FETK=$FETK .."
          cmake -DENABLE_PYTHON=ON -DENABLE_GEOFLOW=ON -DBUILD_DOC=OFF -DBUILD_SHARED_LIBS=ON -DENABLE_FETK=$FETK ..

          echo "NOW RUN MAKE"
          pwd
          make VERBOSE=1 install
          
          echo "LOOK for APBS binary"
          ls $HOME
          find $HOME -type f -name apbs
          echo ""
          ctest .
          cd ../apbs/tests
          bash run_travis_test.sh $HOME/apbs/bin $TEST_SUITE
        env:
          FETK: ON
          TEST_SUITE: born

#    - FETK=OFF  TEST_SUITE=actin-dimer-auto
#    - FETK=OFF  TEST_SUITE=actin-dimer-parallel
#    - FETK=OFF  TEST_SUITE=alkanes
#    - FETK=OFF  TEST_SUITE=born
#    - FETK=OFF  TEST_SUITE=FKBP
#    - FETK=OFF  TEST_SUITE=geoflow
#    - FETK=OFF  TEST_SUITE=hca-bind
#    - FETK=OFF  TEST_SUITE=ion-pmf
#    - FETK=OFF  TEST_SUITE=ion-protein
#    - FETK=OFF  TEST_SUITE=ionize
#    - FETK=OFF  TEST_SUITE=pka-lig
#    - FETK=OFF  TEST_SUITE=point-pmf
#    - FETK=OFF  TEST_SUITE=solv
#    - FETK=OFF  TEST_SUITE=protein-rna
