name: "Copyright Action"
description: "Inserts copyright notice to configured files in repository and creates a pull request"
# From https://github.com/VinnyBabuManjaly/copyright-action

steps:
  # Checking out the repository which is to be actioned
  - uses: actions/checkout@v2
  # Implementing action on repository
  - uses: VinnyBabuManjaly/copyright-action@v1.0.0
    with:
      CopyrightString: |
        # APBS and PDB2PQR licensing
        
        Both APBS and PDB2PQR are distributed under the [BSD-3-Clause open source license](https://choosealicense.com/licenses/bsd-3-clause/).  
        
        ----
        
        ## APBS
        
        APBS -- Adaptive Poisson-Boltzmann Solver
        
          Nathan A. Baker (nathan.baker@pnnl.gov)
          Pacific Northwest National Laboratory
        
          Additional contributing authors listed in the code documentation.
        
        Copyright (c) 2010-2020 Battelle Memorial Institute.
        Developed at the Pacific Northwest National Laboratory, operated by Battelle Memorial Institute, Pacific Northwest Division for the U.S. Department of Energy.
        
        Portions Copyright (c) 2002-2010, Washington University in St. Louis.
        Portions Copyright (c) 2002-2010, Nathan A. Baker.
        Portions Copyright (c) 1999-2002, The Regents of the University of California.
        Portions Copyright (c) 1995, Michael Holst.
        All rights reserved.
        
        Redistribution and use in source and binary forms, with or without
        modification, are permitted provided that the following conditions are met:
        
        * Redistributions of source code must retain the above copyright notice, this
          list of conditions and the following disclaimer.
        
        * Redistributions in binary form must reproduce the above copyright notice,
          this list of conditions and the following disclaimer in the documentation
          and/or other materials provided with the distribution.
        
        * Neither the name of the developer nor the names of its contributors may be
          used to endorse or promote products derived from this software without
          specific prior written permission.
        
        THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
        
        ----
        
        ## PDB2PQR
        
        Copyright (c) 2002-2020, Jens Erik Nielsen, University College Dublin; Nathan A. Baker, Battelle Memorial Institute, Developed at the Pacific Northwest National Laboratory, operated by Battelle Memorial Institute, Pacific Northwest Division for the U.S. Department Energy.; Paul Czodrowski & Gerhard Klebe, University of Marburg.
        
        All rights reserved.
        
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        
        * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        
        * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
        
        * Neither the names of University College Dublin, Battelle Memorial Institute, Pacific Northwest National Laboratory, US Department of Energy, or University of Marburg nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
        
        THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
      FileType: '.py, .c, .h'
      Path: 'apbs/, pdb2pqr'
      IgnorePath: 'apbs/build/, apbs/externals/, build/, contrib/iapbs/, pdb2pqr/build/, pdb2pqr/propka31, apbs/src/.config'
  # Creates pull request with all changes in file
  - name: Create Pull Request
    uses: peter-evans/create-pull-request@v2
    with:
      token: ${{ secrets.COPYRIGHT_ACTION }}